-- CQS Comments
--
-- set search_path to cqs schema;
--

COMMENT ON TABLE Study IS 'Studies';
COMMENT ON COLUMN Study.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN Study.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN Study.studyName IS 'Study Name';
COMMENT ON COLUMN Study.studyDescription IS 'Study Description';
COMMENT ON COLUMN Study.studyStatus IS 'Study Status';
COMMENT ON COLUMN Study.studyPhase IS 'Study Phase';
COMMENT ON COLUMN Study.studySponsor IS 'Study Sponsor';
COMMENT ON COLUMN Study.therapeuticArea IS 'Study Therapeutic Area';
COMMENT ON COLUMN Study.program IS 'Study Program';
COMMENT ON COLUMN Study.medicalIndication IS 'Medical Indication';
COMMENT ON COLUMN Study.studyStartDate IS 'Study Start Date';
COMMENT ON COLUMN Study.studyCompletionDate IS 'Study Completion Date';
COMMENT ON COLUMN Study.studystatusdate IS 'Study Status Date';
COMMENT ON COLUMN Study.isarchived IS 'Archived';
COMMENT ON COLUMN Study.istsdv IS 'Is Targeted Source Data Verification Enabled?';
COMMENT ON COLUMN Study.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE Subject IS 'Subjects';
COMMENT ON COLUMN Subject.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN Subject.siteKey IS 'Site Key';
COMMENT ON COLUMN Subject.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN Subject.siteId IS 'Site Identifier';
COMMENT ON COLUMN Subject.USUBJID IS 'Subject Identifier';
COMMENT ON COLUMN Subject.screenid IS 'Screening Identifier';
COMMENT ON COLUMN Subject.randid IS 'Randomization Identifier';
COMMENT ON COLUMN Subject.status IS 'Subject Status';
COMMENT ON COLUMN Subject.exitDate IS 'Subject Study Exit Date';
COMMENT ON COLUMN Subject.sdvtier IS 'Source Data Verification Tier';
COMMENT ON COLUMN Subject.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN Subject.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE Site IS 'Sites';
COMMENT ON COLUMN Site.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN Site.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN Site.siteId IS 'Site Identifier';
COMMENT ON COLUMN Site.siteName IS 'Site Name';
COMMENT ON COLUMN Site.croid IS 'Site Contract Research Organization Identifier (CRO)';
COMMENT ON COLUMN Site.siteCro IS 'Site Contract Research Organization (CRO)';
COMMENT ON COLUMN Site.siteCountry IS 'Site Country';
COMMENT ON COLUMN Site.siteRegion IS 'Site Region';
COMMENT ON COLUMN Site.siteCreationDate IS 'Site Creation Date';
COMMENT ON COLUMN Site.siteActivationDate IS 'Site Activation Date';
COMMENT ON COLUMN Site.siteDeactivationDate IS 'Site Deactivation Date';
COMMENT ON COLUMN Site.siteInvestigatorName IS 'Site Investigator Name';
COMMENT ON COLUMN Site.siteCRAName IS 'Site CRA Name';
COMMENT ON COLUMN Site.siteaddress1 IS 'Site Address Line 1';
COMMENT ON COLUMN Site.siteaddress2 IS 'Site Address Line 2';
COMMENT ON COLUMN Site.sitecity IS 'Site City';
COMMENT ON COLUMN Site.sitestate IS 'Site State';
COMMENT ON COLUMN Site.sitepostal IS 'Site Postal Code';
COMMENT ON COLUMN Site.sitestatus IS 'Site Status';
COMMENT ON COLUMN Site.sitestatusdate IS 'Site Status Date';
COMMENT ON COLUMN Site.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE Query IS 'Queries';
COMMENT ON COLUMN Query.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN Query.studyid IS 'Study Identifier';
COMMENT ON COLUMN Query.siteId IS 'Site Identifier';
COMMENT ON COLUMN Query.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN Query.queryId IS 'Query Identifier';
COMMENT ON COLUMN Query.formid IS 'Query Page';
COMMENT ON COLUMN Query.fieldid IS 'Query Field';
COMMENT ON COLUMN Query.queryText IS 'Query Text';
COMMENT ON COLUMN Query.queryType IS 'Query Type';
COMMENT ON COLUMN Query.queryStatus IS 'Query Status (Open, Answered, Closed)';
COMMENT ON COLUMN Query.queryOpenedDate IS 'Query Open Date';
COMMENT ON COLUMN Query.queryResponseDate IS 'Query Response Date';
COMMENT ON COLUMN Query.queryClosedDate IS 'Query Closed Date';
COMMENT ON COLUMN Query.visit IS 'Visit Name';
COMMENT ON COLUMN Query.formseq IS 'Form Sequence';
COMMENT ON COLUMN Query.log_num IS 'Log Number';
COMMENT ON COLUMN Query.querycreator IS 'Query Creator';
COMMENT ON COLUMN Query.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN Query.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE SiteMonitoringVisitSchedule IS 'Site Monitoring Visit Schedules';
COMMENT ON COLUMN SiteMonitoringVisitSchedule.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN SiteMonitoringVisitSchedule.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN SiteMonitoringVisitSchedule.siteId IS 'Site Identifier';
COMMENT ON COLUMN SiteMonitoringVisitSchedule.plannedVisitDate IS 'Planned Visit Date';
COMMENT ON COLUMN SiteMonitoringVisitSchedule.visitName IS 'Visit Name';
COMMENT ON COLUMN SiteMonitoringVisitSchedule.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN SiteMonitoringVisitSchedule.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE SiteMonitoringVisit IS 'Site Monitoring Visits';
COMMENT ON COLUMN SiteMonitoringVisit.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN SiteMonitoringVisit.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN SiteMonitoringVisit.siteId IS 'Site Identifier';
COMMENT ON COLUMN SiteMonitoringVisit.visitName IS 'Site Monitoring Visit Name';
COMMENT ON COLUMN SiteMonitoringVisit.visitDate IS 'Site Monitoring Visit Date';
COMMENT ON COLUMN SiteMonitoringVisit.smvipyn IS 'IP Accountability performed y/n';
COMMENT ON COLUMN SiteMonitoringVisit.smvpiyn IS 'PI Present y/n';
COMMENT ON COLUMN SiteMonitoringVisit.smvtrvld IS 'Site Monitoring Visit Travel Duration';
COMMENT ON COLUMN SiteMonitoringVisit.smvtrvlu IS 'Site Monitoring Visit Travel Duration Unit';
COMMENT ON COLUMN SiteMonitoringVisit.smvvtype IS 'Site Monitoring Visit Type';
COMMENT ON COLUMN SiteMonitoringVisit.smvmethd IS 'Site Monitoring Visit Method';
COMMENT ON COLUMN SiteMonitoringVisit.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN SiteMonitoringVisit.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE StudyMilestone IS 'Study Milestones';
COMMENT ON COLUMN StudyMilestone.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN StudyMilestone.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN StudyMilestone.milestoneSeq IS 'Milestone Sequence';
COMMENT ON COLUMN StudyMilestone.milestoneLabel IS 'Milestone Label';
COMMENT ON COLUMN StudyMilestone.milestoneType IS 'Milestone Type (Original, Baseline, Planned, Actual)';
COMMENT ON COLUMN StudyMilestone.expectedDate IS 'Expected Date';
COMMENT ON COLUMN StudyMilestone.isMandatory IS 'Is Milestone Mandatory? (true = yes, false = no)';
COMMENT ON COLUMN StudyMilestone.isCriticalPath IS 'Is Milestone on Critical Path (true = yes, false = no)';
COMMENT ON COLUMN StudyMilestone.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN StudyMilestone.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE SiteMilestone IS 'Site Milestones';
COMMENT ON COLUMN SiteMilestone.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN SiteMilestone.siteId IS 'Site Identifier';
COMMENT ON COLUMN SiteMilestone.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN SiteMilestone.milestoneSeq IS 'Milestone Sequence';
COMMENT ON COLUMN SiteMilestone.milestoneLabel IS 'Milestone Label';
COMMENT ON COLUMN SiteMilestone.milestoneType IS 'Milestone Type (Original, Baseline, Planned, Actual)';
COMMENT ON COLUMN SiteMilestone.expectedDate IS 'Expected Date';
COMMENT ON COLUMN SiteMilestone.isMandatory IS 'Is Milestone Mandatory? (true = yes, false = no)';
COMMENT ON COLUMN SiteMilestone.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN SiteMilestone.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE AE IS 'Adverse Events';
COMMENT ON COLUMN AE.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN AE.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN AE.siteId IS 'Site Identifier';
COMMENT ON COLUMN AE.USUBJID IS 'Subject Identifier';
COMMENT ON COLUMN AE.AETERM IS 'Adverse Event Coded Term';
COMMENT ON COLUMN AE.AEVERBATIM IS 'Adverse Event Verbatim Term';
COMMENT ON COLUMN AE.AEBODSYS IS 'Adverse Event Body System (or SOC)';
COMMENT ON COLUMN AE.AESTDTC IS 'Adverse Event Start Date';
COMMENT ON COLUMN AE.AEENDTC IS 'Adverse Event End Date';
COMMENT ON COLUMN AE.AESEV IS 'Severity (e.g. Mild, Moderate, Severe)';
COMMENT ON COLUMN AE.AESER IS 'Serious (e.g. Serious, Non-Serious, Unknown)';
COMMENT ON COLUMN AE.AERELNST IS 'Is AE Related to the Drug/Device? (e.g. Yes, No, or Unknown)';
COMMENT ON COLUMN AE.AESEQ IS 'Adverse Event Sequence Number';
COMMENT ON COLUMN AE.aesttm IS 'Adverse Event Start Time';
COMMENT ON COLUMN AE.aeentm IS 'Adverse Event End Time';
COMMENT ON COLUMN AE.aellt IS 'Lowest Level Term';
COMMENT ON COLUMN AE.aelltcd IS 'Lowest Level Term Code';
COMMENT ON COLUMN AE.aeptcd IS 'Preferred Term Code';
COMMENT ON COLUMN AE.aehlt IS 'High Level Term';
COMMENT ON COLUMN AE.aehltcd IS 'High Level Term Code';
COMMENT ON COLUMN AE.aehlgt IS 'High Level Group Term';
COMMENT ON COLUMN AE.aehlgtcd IS 'High Level Group Term Code';
COMMENT ON COLUMN AE.aebdsycd IS 'Body System or Organ Class Code';
COMMENT ON COLUMN AE.aesoc IS 'Primary System Organ Class';
COMMENT ON COLUMN AE.aesoccd IS 'Primary System Organ Class Code';
COMMENT ON COLUMN AE.aeacn IS 'Action Taken with Study Treatment';
COMMENT ON COLUMN AE.aeout IS 'Adverse Event Outcome';
COMMENT ON COLUMN AE.aetox IS 'AE Toxicity';
COMMENT ON COLUMN AE.aetoxgr IS 'AE Toxicity Grade';
COMMENT ON COLUMN AE.aeongo IS 'AE Ongoing';
COMMENT ON COLUMN AE.aecomm IS 'AE Comments';
COMMENT ON COLUMN AE.aespid IS 'AE Identifier';
COMMENT ON COLUMN AE.aestdtc_iso IS 'AE Start Date / Time (ISO)';
COMMENT ON COLUMN AE.aeendtc_iso IS 'AE End Date / Time (ISO)';
COMMENT ON COLUMN AE.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN AE.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE DV IS 'Protocol Deviations';
COMMENT ON COLUMN DV.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN DV.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN DV.siteId IS 'Site Identifier';
COMMENT ON COLUMN DV.USUBJID IS 'Subject Identifier';
COMMENT ON COLUMN DV.visit IS 'Folder (aka Visit)';
COMMENT ON COLUMN DV.formid IS 'Form';
COMMENT ON COLUMN DV.DVSEQ IS 'Deviation Sequence';
COMMENT ON COLUMN DV.DVCAT IS 'Deviation Category';
COMMENT ON COLUMN DV.DVTERM IS 'Deviation Term';
COMMENT ON COLUMN DV.DVSTDTC IS 'Deviation Start Date';
COMMENT ON COLUMN DV.DVENDTC IS 'Deviation End Date';
COMMENT ON COLUMN DV.DVSCAT IS 'Subcategory for Protocol Deviation';
COMMENT ON COLUMN DV.DVID IS 'Deviation Identifier';
COMMENT ON COLUMN DV.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN DV.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE DVSITE IS 'Site Protocol Deviations';
COMMENT ON COLUMN DVSITE.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN DVSITE.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN DVSITE.siteId IS 'Site Identifier';
COMMENT ON COLUMN DVSITE.DVSEQ IS 'Deviation Sequence';
COMMENT ON COLUMN DVSITE.DVCAT IS 'Deviation Category';
COMMENT ON COLUMN DVSITE.DVTERM IS 'Deviation Term';
COMMENT ON COLUMN DVSITE.DVSTDTC IS 'Deviation Start Date';
COMMENT ON COLUMN DVSITE.DVENDTC IS 'Deviation End Date';
COMMENT ON COLUMN DVSITE.DVSCAT IS 'Subcategory for Protocol Deviation';
COMMENT ON COLUMN DVSITE.DVID IS 'Deviation Identifier';
COMMENT ON COLUMN DVSITE.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN DVSITE.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE DS IS 'Subject Disposition';
COMMENT ON COLUMN DS.COMPREHENDID IS 'Comprehend Identifier';
COMMENT ON COLUMN DS.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN DS.SITEID IS 'Site Identifier';
COMMENT ON COLUMN DS.USUBJID IS 'Subject Identifier';
COMMENT ON COLUMN DS.DSSEQ IS 'Subject Disposition Sequence (correlates to Category)';
COMMENT ON COLUMN DS.DSCAT IS 'Subject Disposition Category';
COMMENT ON COLUMN DS.DSTERM IS 'Subject Disposition Term';
COMMENT ON COLUMN DS.DSSTDTC IS 'Subject Disposition Event Date';
COMMENT ON COLUMN DS.DSSCAT IS 'Subject Disposition Sub-category (e.g. Reason)';
COMMENT ON COLUMN DS.DSGRPID IS 'Group ID';
COMMENT ON COLUMN DS.DSREFID IS 'Reference ID';
COMMENT ON COLUMN DS.DSSPID IS 'Sponsor ID';
COMMENT ON COLUMN DS.DSDECOD IS 'Controlled Terminology for Disposition Term';
COMMENT ON COLUMN DS.VISIT IS 'Visit Name';
COMMENT ON COLUMN DS.VISITNUM IS 'Visit Number';
COMMENT ON COLUMN DS.VISITDY IS 'Planned Study Day of Visit';
COMMENT ON COLUMN DS.EPOCH IS 'Stage of Disposition Event';
COMMENT ON COLUMN DS.DSDTC IS 'Date/Time of Collection';
COMMENT ON COLUMN DS.DSSTDY IS 'Study Day of Start of Disposition Event';
COMMENT ON COLUMN DS.OBJECTUNIQUEKEY IS 'Object Unique Key';
COMMENT ON COLUMN DS.COMPREHEND_UPDATE_TIME IS 'Comprehend Update Time';

COMMENT ON TABLE SV IS 'Subject Visits';
COMMENT ON COLUMN SV.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN SV.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN SV.siteId IS 'Site Identifier';
COMMENT ON COLUMN SV.USUBJID IS 'Subject Identifier';
COMMENT ON COLUMN SV.VISITNUM IS 'Visit Number';
COMMENT ON COLUMN SV.VISIT IS 'Visit';
COMMENT ON COLUMN SV.visitseq IS 'Sequence Number (within a given visit) (aka subevent)';
COMMENT ON COLUMN SV.SVSTDTC IS 'Visit Start Date';
COMMENT ON COLUMN SV.SVENDTC IS 'Visit End Date';
COMMENT ON COLUMN SV.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN SV.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE TV IS 'Study Visit Schedule';
COMMENT ON COLUMN TV.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN TV.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN TV.VISITNUM IS 'Visit Number';
COMMENT ON COLUMN TV.VISIT IS 'Visit';
COMMENT ON COLUMN TV.VISITDY IS 'Visit Day (from start of study)';
COMMENT ON COLUMN TV.visitwindowbefore IS 'Acceptable Visit Window Before Visit Day (in days)';
COMMENT ON COLUMN TV.visitwindowafter IS 'Acceptable Visit Window After Visit Day (in days)';
COMMENT ON COLUMN TV.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN TV.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE FormDef IS 'Form Definition';
COMMENT ON COLUMN FormDef.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN FormDef.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN FormDef.formId IS 'Form Identifier';
COMMENT ON COLUMN FormDef.formName IS 'Form Name';
COMMENT ON COLUMN FormDef.isPrimaryEndpoint IS 'Is Primary Endpoint?';
COMMENT ON COLUMN FormDef.isSecondaryEndpoint IS 'Is Secondary Endpoint?';
COMMENT ON COLUMN FormDef.isSDV IS 'Is Source Data Verified Required?';
COMMENT ON COLUMN FormDef.isRequired IS 'Is the Form Required?';
COMMENT ON COLUMN FormDef.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN FormDef.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE FieldDef IS 'Field Definition';
COMMENT ON COLUMN FieldDef.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN FieldDef.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN FieldDef.formId IS 'Form Identifier';
COMMENT ON COLUMN FieldDef.fieldId IS 'Field Identifier';
COMMENT ON COLUMN FieldDef.fieldName IS 'Field Name';
COMMENT ON COLUMN FieldDef.isPrimaryEndpoint IS 'Is Primary Endpoint?';
COMMENT ON COLUMN FieldDef.isSecondaryEndpoint IS 'Is Secondary Endpoint?';
COMMENT ON COLUMN FieldDef.isSDV IS 'Is Source Data Verified Required?';
COMMENT ON COLUMN FieldDef.isRequired IS 'Is the Field Required for the Form?';
COMMENT ON COLUMN FieldDef.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN FieldDef.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE FieldData IS 'Field Data';
COMMENT ON COLUMN FieldData.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN FieldData.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN FieldData.siteId IS 'Site Identifier';
COMMENT ON COLUMN FieldData.USUBJID IS 'Subject Identifier';
COMMENT ON COLUMN FieldData.formId IS 'Form Identifier';
COMMENT ON COLUMN FieldData.formseq IS 'Form Sequence';
COMMENT ON COLUMN FieldData.fieldId IS 'Field Identifier';
COMMENT ON COLUMN FieldData.fieldseq IS 'Field Sequence';
COMMENT ON COLUMN FieldData.visit IS 'Visit';
COMMENT ON COLUMN FieldData.visitSeq IS 'Visit Sequence';
COMMENT ON COLUMN FieldData.log_num IS 'Log Number';
COMMENT ON COLUMN FieldData.dataValue IS 'Data Values (aka Subject Response)';
COMMENT ON COLUMN FieldData.SourceRecordPrimaryKey IS 'Data Values (Source Record Primary Key)';
COMMENT ON COLUMN FieldData.SourceRecordDate IS 'Data Values (Source Record Entry Date)';
COMMENT ON COLUMN FieldData.IsDeleted IS 'Data Values (Deleted Flag)';
COMMENT ON COLUMN FieldData.dataEntryDate IS 'Data Entry Date';
COMMENT ON COLUMN FieldData.dataCollectedDate IS 'Data Collected Date';
COMMENT ON COLUMN FieldData.sdvDate IS 'Source Data Verified Date';
COMMENT ON COLUMN FieldData.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN FieldData.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE FormData IS 'Form Data';
COMMENT ON COLUMN FormData.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN FormData.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN FormData.siteId IS 'Site Identifier';
COMMENT ON COLUMN FormData.USUBJID IS 'Subject Identifier';
COMMENT ON COLUMN FormData.formId IS 'Form Identifier';
COMMENT ON COLUMN FormData.formseq IS 'Form Sequence';
COMMENT ON COLUMN FormData.visit IS 'Visit';
COMMENT ON COLUMN FormData.visitSeq IS 'Visit Sequence';
COMMENT ON COLUMN FormData.dataEntryDate IS 'Data Entry Date';
COMMENT ON COLUMN FormData.dataCollectedDate IS 'Data Collected Date';
COMMENT ON COLUMN FormData.sdvDate IS 'Source Data Verified Date';
COMMENT ON COLUMN FormData.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN FormData.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE IpAccountability IS 'Investigational Product (IP) Accountability Data';
COMMENT ON COLUMN IpAccountability.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN IpAccountability.studyid IS 'Study Identifier';
COMMENT ON COLUMN IpAccountability.siteId IS 'Site Identifier';
COMMENT ON COLUMN IpAccountability.ipName IS 'Investigational Product Name';
COMMENT ON COLUMN IpAccountability.ipId IS 'Batch, Lot, or Serial Number Identifier';
COMMENT ON COLUMN IpAccountability.ipQuantity IS 'Amount sent of Investigational Product';
COMMENT ON COLUMN IpAccountability.ipUnit IS 'Unit of Measurement';
COMMENT ON COLUMN IpAccountability.ipExpirationDate IS 'Expiration Date';
COMMENT ON COLUMN IpAccountability.ipDate IS 'State Event Date';
COMMENT ON COLUMN IpAccountability.ipSeq IS 'State Sequence Number';
COMMENT ON COLUMN IpAccountability.ipState IS 'State Term';
COMMENT ON COLUMN IpAccountability.ipReason IS 'Reason (entered for Product Loss)';
COMMENT ON COLUMN IpAccountability.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN IpAccountability.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE SiteIssue IS 'Site Issues';
COMMENT ON COLUMN SiteIssue.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN SiteIssue.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN SiteIssue.siteId IS 'Site Identifier';
COMMENT ON COLUMN SiteIssue.issueId IS 'Issue Identifier';
COMMENT ON COLUMN SiteIssue.issueText IS 'Issue Text';
COMMENT ON COLUMN SiteIssue.issueType IS 'Issue Type';
COMMENT ON COLUMN SiteIssue.issueStatus IS 'Issue Status (e.g. Open, Answered, Closed)';
COMMENT ON COLUMN SiteIssue.issueOpenedDate IS 'Issue Open Date';
COMMENT ON COLUMN SiteIssue.issueResponseDate IS 'Issue Response Date';
COMMENT ON COLUMN SiteIssue.issueClosedDate IS 'Issue Closed Date';
COMMENT ON COLUMN SiteIssue.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN SiteIssue.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE DM IS 'Demographics';
COMMENT ON COLUMN DM.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN DM.STUDYID IS 'Study Identifier';
COMMENT ON COLUMN DM.siteId IS 'Site Identifier';
COMMENT ON COLUMN DM.USUBJID IS 'Subject Identifier';
COMMENT ON COLUMN DM.VISITNUM IS 'Visit Number';
COMMENT ON COLUMN DM.VISIT IS 'Visit';
COMMENT ON COLUMN DM.dmdtc IS 'Date of Collection';
COMMENT ON COLUMN DM.BRTHDTC IS 'Date of Birth';
COMMENT ON COLUMN DM.AGE IS 'Age';
COMMENT ON COLUMN DM.SEX IS 'Sex';
COMMENT ON COLUMN DM.RACE IS 'Race';
COMMENT ON COLUMN DM.ETHNICITY IS 'Ethnicity';
COMMENT ON COLUMN DM.ARMCD IS 'Planned Arm Code';
COMMENT ON COLUMN DM.ARM IS 'Description of Planned Arm';
COMMENT ON COLUMN DM.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN DM.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE comprehendTermMap IS 'Comprehend Term Map';
COMMENT ON COLUMN comprehendTermMap.tablename IS 'Table Name';
COMMENT ON COLUMN comprehendTermMap.columnname IS 'Column Name';
COMMENT ON COLUMN comprehendTermMap.studyid IS 'Study Identifier';
COMMENT ON COLUMN comprehendTermMap.comprehendterm IS 'Comprehend Term';
COMMENT ON COLUMN comprehendTermMap.originalterm IS 'Original Term (for display)';

COMMENT ON TABLE ie IS 'InclusionExclusion (IE) Data';
COMMENT ON COLUMN ie.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN ie.studyid IS 'Study Identifier';
COMMENT ON COLUMN ie.siteid IS 'Site Identifier';
COMMENT ON COLUMN ie.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN ie.visitnum IS 'Visit Number';
COMMENT ON COLUMN ie.visit IS 'Visit';
COMMENT ON COLUMN ie.iedtc IS 'Date of Collection';
COMMENT ON COLUMN ie.ieseq IS 'InclusionExclusion Sequence Number';
COMMENT ON COLUMN ie.ietestcd IS 'Test Identifier';
COMMENT ON COLUMN ie.ietest IS 'Test Name';
COMMENT ON COLUMN ie.iecat IS 'InclusionExclusion Category';
COMMENT ON COLUMN ie.iescat IS 'InclusionExclusion Sub-Category';
COMMENT ON COLUMN ie.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN ie.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE visitform IS 'Visit Form Data';
COMMENT ON COLUMN visitform.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN visitform.studyid IS 'Study Identifier';
COMMENT ON COLUMN visitform.visitnum IS 'Visit Number';
COMMENT ON COLUMN visitform.visit IS 'Visit';
COMMENT ON COLUMN visitform.formid IS 'Form Identifier';
COMMENT ON COLUMN visitform.isrequired IS 'Is Required?';
COMMENT ON COLUMN visitform.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN visitform.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE lb IS 'Lab Data';
COMMENT ON COLUMN lb.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN lb.studyid IS 'Study Identifier';
COMMENT ON COLUMN lb.siteid IS 'Site Identifier';
COMMENT ON COLUMN lb.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN lb.visit IS 'Visit Name';
COMMENT ON COLUMN lb.lbdtc IS 'Date/Time of Specimen Collection';
COMMENT ON COLUMN lb.lbdy IS 'Study Day of Specifimen Collection';
COMMENT ON COLUMN lb.lbseq IS 'Sequence Number';
COMMENT ON COLUMN lb.lbtestcd IS 'Lab Test or Examination Short Name';
COMMENT ON COLUMN lb.lbtest IS 'Lab Test or Examination Name';
COMMENT ON COLUMN lb.lbcat IS 'Category for Lab Test';
COMMENT ON COLUMN lb.lbscat IS 'Subcategory for Lab Test';
COMMENT ON COLUMN lb.lbspec IS 'Specimen Type';
COMMENT ON COLUMN lb.lbmethod IS 'Method of Test or Examination';
COMMENT ON COLUMN lb.lborres IS 'Result or Findings in Original Units';
COMMENT ON COLUMN lb.lbstat IS 'Completion Status';
COMMENT ON COLUMN lb.lbreasnd IS 'Reason Test Not Done';
COMMENT ON COLUMN lb.lbstnrlo IS 'Reference Range Lower Limit-Std Units';
COMMENT ON COLUMN lb.lbstnrhi IS 'Reference Range Upper Limit-Std Units';
COMMENT ON COLUMN lb.lborresu IS 'Original Units';
COMMENT ON COLUMN lb.lbstresn IS 'Numeric Result/Finding in Standard Units';
COMMENT ON COLUMN lb.lbstresu IS 'Standard Units';
COMMENT ON COLUMN lb.lbtm IS 'Time of Specimen Collection';
COMMENT ON COLUMN lb.lbblfl IS 'Baseline Flag';
COMMENT ON COLUMN lb.lbnrind IS 'Reference Range Indicator';
COMMENT ON COLUMN lb.lbornrhi IS 'Reference Range Upper Limit in Orig Unit';
COMMENT ON COLUMN lb.lbornrlo IS 'Reference Range Lower Limit in Orig Unit';
COMMENT ON COLUMN lb.lbstresc IS 'Character Result/Finding in Std Format';
COMMENT ON COLUMN lb.lbenint IS 'Planned End of Assessment Interval';
COMMENT ON COLUMN lb.lbevlint IS 'Evaluation Interval';
COMMENT ON COLUMN lb.lblat IS 'Laterality';
COMMENT ON COLUMN lb.lblloq IS 'Lower Limit of Quantitation';
COMMENT ON COLUMN lb.lbloc IS 'Location';
COMMENT ON COLUMN lb.lbpos IS 'Position';
COMMENT ON COLUMN lb.lbstint IS 'Planned Start of Assessment Interval';
COMMENT ON COLUMN lb.lbuloq IS 'Upper Limit of Quantitation';
COMMENT ON COLUMN lb.lbclsig IS 'Clinically Significant';
COMMENT ON COLUMN lb.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN lb.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE studyplannedstatistic IS 'Study Planned Statistics';
COMMENT ON COLUMN studyplannedstatistic.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN studyplannedstatistic.studyid IS 'Study Identifier';
COMMENT ON COLUMN studyplannedstatistic.statcat IS 'Statistic Category';
COMMENT ON COLUMN studyplannedstatistic.statsubcat IS 'Statistic SubCategory';
COMMENT ON COLUMN studyplannedstatistic.statval IS 'Statistic Value';
COMMENT ON COLUMN studyplannedstatistic.statunit IS 'Statistic Unit';
COMMENT ON COLUMN studyplannedstatistic.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN studyplannedstatistic.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE siteplannedstatistic IS 'Site Planned Statistics';
COMMENT ON COLUMN siteplannedstatistic.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN siteplannedstatistic.studyid IS 'Study Identifier';
COMMENT ON COLUMN siteplannedstatistic.siteid IS 'Site Identifier';
COMMENT ON COLUMN siteplannedstatistic.statcat IS 'Statistic Category';
COMMENT ON COLUMN siteplannedstatistic.statsubcat IS 'Statistic SubCategory';
COMMENT ON COLUMN siteplannedstatistic.statval IS 'Statistic Value';
COMMENT ON COLUMN siteplannedstatistic.statunit IS 'Statistic Unit';
COMMENT ON COLUMN siteplannedstatistic.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN siteplannedstatistic.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE SiteResource IS 'Site Resources';
COMMENT ON COLUMN SiteResource.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN SiteResource.studyid IS 'Study Identifier';
COMMENT ON COLUMN SiteResource.siteid IS 'Site Identifier';
COMMENT ON COLUMN SiteResource.resourceType IS 'Resource Type';
COMMENT ON COLUMN SiteResource.resourceName IS 'Resource Name';
COMMENT ON COLUMN SiteResource.resourceSeq IS 'Resource Sequence Number';
COMMENT ON COLUMN SiteResource.resourceStDtc IS 'Resource Start Date';
COMMENT ON COLUMN SiteResource.resourceEndDtc IS 'Resource End Date';
COMMENT ON COLUMN SiteResource.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN SiteResource.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE cm IS 'Concomitant Medications Data';
COMMENT ON COLUMN cm.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN cm.studyid IS 'Study Identifier';
COMMENT ON COLUMN cm.siteid IS 'Site Identifier';
COMMENT ON COLUMN cm.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN cm.cmseq IS 'Sequence Number';
COMMENT ON COLUMN cm.cmtrt IS 'Reported Name of Drug, Med, or Therapy';
COMMENT ON COLUMN cm.cmmodify IS 'Modified Reported Name';
COMMENT ON COLUMN cm.cmdecod IS 'Standardized Medication Name';
COMMENT ON COLUMN cm.cmcat IS 'Category for Medication';
COMMENT ON COLUMN cm.cmscat IS 'Subcategory for Medication';
COMMENT ON COLUMN cm.cmindc IS 'Indication';
COMMENT ON COLUMN cm.cmdose IS 'Dose per Administration';
COMMENT ON COLUMN cm.cmdosu IS 'Dose Units';
COMMENT ON COLUMN cm.cmdosfrm IS 'Dose Form';
COMMENT ON COLUMN cm.cmdosfrq IS 'Dosing Frequency Per Interval';
COMMENT ON COLUMN cm.cmdostot IS 'Total Daily Dose using CMDOSU';
COMMENT ON COLUMN cm.cmroute IS 'Route of Administration';
COMMENT ON COLUMN cm.cmstdtc IS 'Start Date/Time of Medication';
COMMENT ON COLUMN cm.cmendtc IS 'End Date/Time of Medication';
COMMENT ON COLUMN cm.cmsttm IS 'Start Time of Medication';
COMMENT ON COLUMN cm.cmentm IS 'End Time of Medication';
COMMENT ON COLUMN cm.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN cm.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE siteplannedexpenditure IS 'Site Planned Expenditure Data';
COMMENT ON COLUMN siteplannedexpenditure.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN siteplannedexpenditure.studyid IS 'Study Identifier';
COMMENT ON COLUMN siteplannedexpenditure.siteid IS 'Site Identifier';
COMMENT ON COLUMN siteplannedexpenditure.exptype IS 'Expenditure Type (Planned or Actual)';
COMMENT ON COLUMN siteplannedexpenditure.expCat IS 'Expenditure Category';
COMMENT ON COLUMN siteplannedexpenditure.expSubCat IS 'Expenditure SubCategory';
COMMENT ON COLUMN siteplannedexpenditure.expLabel IS 'Expenditure Label';
COMMENT ON COLUMN siteplannedexpenditure.expdtc IS 'Expenditure Date';
COMMENT ON COLUMN siteplannedexpenditure.expSeq IS 'Expenditure Sequence';
COMMENT ON COLUMN siteplannedexpenditure.expAmount IS 'Amount Original Units';
COMMENT ON COLUMN siteplannedexpenditure.expUnit IS 'Original Units';
COMMENT ON COLUMN siteplannedexpenditure.expAmountStd IS 'Amount Standard Units';
COMMENT ON COLUMN siteplannedexpenditure.expUnitStd IS 'Standard Units';
COMMENT ON COLUMN siteplannedexpenditure.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN siteplannedexpenditure.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE siteplannedenrollment IS 'Site Planned Enrollment Data';
COMMENT ON COLUMN siteplannedenrollment.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN siteplannedenrollment.studyid IS 'Study Identifier';
COMMENT ON COLUMN siteplannedenrollment.siteid IS 'Site Identifier';
COMMENT ON COLUMN siteplannedenrollment.frequency IS 'Frequency (e.g. Monthly)';
COMMENT ON COLUMN siteplannedenrollment.endDate IS 'Period End Date';
COMMENT ON COLUMN siteplannedenrollment.enrollmentType IS 'Enrollment Type (Planned)';
COMMENT ON COLUMN siteplannedenrollment.enrollmentcount IS 'Enrollment Count (number of subjects)';
COMMENT ON COLUMN siteplannedenrollment.objectUniqueKey IS 'Object Unique Key';
COMMENT ON COLUMN siteplannedenrollment.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE ex IS 'Exposure';
COMMENT ON COLUMN ex.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN ex.studyid IS 'Study Identifier';
COMMENT ON COLUMN ex.siteid IS 'Site Identifier';
COMMENT ON COLUMN ex.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN ex.visit IS 'Visit';
COMMENT ON COLUMN ex.exseq IS 'Exposure Sequence Number';
COMMENT ON COLUMN ex.extrt IS 'Name of Actual Treatment';
COMMENT ON COLUMN ex.excat IS 'Category for Treatment';
COMMENT ON COLUMN ex.exscat IS 'Subcategory for Treatment';
COMMENT ON COLUMN ex.exdose IS 'Dose per Administration';
COMMENT ON COLUMN ex.exdostxt IS 'Dose Description';
COMMENT ON COLUMN ex.exdosu IS 'Dose Unit';
COMMENT ON COLUMN ex.exdosfrm IS 'Dose Form';
COMMENT ON COLUMN ex.exdosfrq IS 'Dose Frequency Per Interval';
COMMENT ON COLUMN ex.exdostot IS 'Total Daily Dose';
COMMENT ON COLUMN ex.exstdtc IS 'Treatment Start Date';
COMMENT ON COLUMN ex.exsttm IS 'Treatment Start Time';
COMMENT ON COLUMN ex.exstdy IS 'Treatment Start Study Day';
COMMENT ON COLUMN ex.exendtc IS 'Treatment End Date';
COMMENT ON COLUMN ex.exendy IS 'Treatment End Study Day';
COMMENT ON COLUMN ex.exendtm IS 'Treatment End Time';
COMMENT ON COLUMN ex.exdur IS 'Duration of Treatment';
COMMENT ON COLUMN ex.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN ex.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE studycro IS 'Study Contract Research Organization';
COMMENT ON COLUMN studycro.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN studycro.crokey IS 'Contract Research Organization Key';
COMMENT ON COLUMN studycro.studyid IS 'Study Identifier';
COMMENT ON COLUMN studycro.croid IS 'Contract Research Organization Identifier';
COMMENT ON COLUMN studycro.croname IS 'Contract Research Organization Name';
COMMENT ON COLUMN studycro.crodescription IS 'Contract Research Organization Description';
COMMENT ON COLUMN studycro.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN studycro.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE mh IS 'Medical History';
COMMENT ON COLUMN mh.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN mh.studyid IS 'Study Identifier';
COMMENT ON COLUMN mh.siteid IS 'Site Identifier';
COMMENT ON COLUMN mh.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN mh.mhseq IS 'Medical History Sequence Number';
COMMENT ON COLUMN mh.mhterm IS 'Medical History Verbatim Term';
COMMENT ON COLUMN mh.mhdecod IS 'Medical History Coded Term';
COMMENT ON COLUMN mh.mhcat IS 'Category for Medical History';
COMMENT ON COLUMN mh.mhscat IS 'Subcategory for Medical History';
COMMENT ON COLUMN mh.mhbodsys IS 'Medical History Body System';
COMMENT ON COLUMN mh.mhstdtc IS 'Medical History Start Date';
COMMENT ON COLUMN mh.mhsttm IS 'Medical History Start Time';
COMMENT ON COLUMN mh.mhendtc IS 'Medical History End Date';
COMMENT ON COLUMN mh.mhendtm IS 'Medical History End Time';
COMMENT ON COLUMN mh.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN mh.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE studyplannedrecruitment IS 'Study Planned Recruitment';
COMMENT ON COLUMN studyplannedrecruitment.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN studyplannedrecruitment.studyid IS 'Study Identifier';
COMMENT ON COLUMN studyplannedrecruitment.category IS 'Category';
COMMENT ON COLUMN studyplannedrecruitment.frequency IS 'Frequency';
COMMENT ON COLUMN studyplannedrecruitment.enddate IS 'Period End Date';
COMMENT ON COLUMN studyplannedrecruitment.type IS 'Recruitment Type';
COMMENT ON COLUMN studyplannedrecruitment.recruitmentcount IS 'Recruitment Count';
COMMENT ON COLUMN studyplannedrecruitment.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN studyplannedrecruitment.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE qs IS 'Questionnaire';
COMMENT ON COLUMN qs.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN qs.studyid IS 'Study Identifier';
COMMENT ON COLUMN qs.siteid IS 'Site Identifier';
COMMENT ON COLUMN qs.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN qs.qsseq IS 'Question Sequence Number';
COMMENT ON COLUMN qs.qstestcd IS 'Question Short Name';
COMMENT ON COLUMN qs.qstest IS 'Question Name';
COMMENT ON COLUMN qs.qscat IS 'Category for Question';
COMMENT ON COLUMN qs.qsscat IS 'Subcategory for Question';
COMMENT ON COLUMN qs.qsorres IS 'Finding in Original Units';
COMMENT ON COLUMN qs.qsorresu IS 'Original Units';
COMMENT ON COLUMN qs.qsstresc IS 'Character Result/Finding in Std Format';
COMMENT ON COLUMN qs.qsstresn IS 'Numeric Finding in Standard Units';
COMMENT ON COLUMN qs.qsstresu IS 'Standard Units';
COMMENT ON COLUMN qs.qsstat IS 'Completion Status';
COMMENT ON COLUMN qs.qsblfl IS 'Baseline Flag';
COMMENT ON COLUMN qs.visit IS 'Visit Name';
COMMENT ON COLUMN qs.qsdtc IS 'Date/Time of Finding';
COMMENT ON COLUMN qs.qstm IS 'Time of Finding';
COMMENT ON COLUMN qs.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN qs.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE vs IS 'Vital Signs';
COMMENT ON COLUMN vs.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN vs.studyid IS 'Study Identifier';
COMMENT ON COLUMN vs.siteid IS 'Site Identifier';
COMMENT ON COLUMN vs.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN vs.vsseq IS 'Vital Signs Sequence Number';
COMMENT ON COLUMN vs.vstestcd IS 'Vital Signs Test Short Name';
COMMENT ON COLUMN vs.vstest IS 'Vital Signs Test Name';
COMMENT ON COLUMN vs.vscat IS 'Category for Vital Signs';
COMMENT ON COLUMN vs.vsscat IS 'Subcategory for Vital Signs';
COMMENT ON COLUMN vs.vspos IS 'Vital Signs Position of Subject';
COMMENT ON COLUMN vs.vsorres IS 'Result/Finding in Original Units';
COMMENT ON COLUMN vs.vsorresu IS 'Original Units';
COMMENT ON COLUMN vs.vsstresn IS 'Numeric Result/Finding in Standard Units';
COMMENT ON COLUMN vs.vsstresu IS 'Standard Units';
COMMENT ON COLUMN vs.vsstat IS 'Completion Status';
COMMENT ON COLUMN vs.vsloc IS 'Location of Vital Signs Measurement';
COMMENT ON COLUMN vs.vsblfl IS 'Baseline Flag';
COMMENT ON COLUMN vs.visit IS 'Visit Name';
COMMENT ON COLUMN vs.vsdtc IS 'Date/Time of Measurements';
COMMENT ON COLUMN vs.vstm IS 'Time of Measurement';
COMMENT ON COLUMN vs.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN vs.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE eg IS 'ECG Test Results';
COMMENT ON COLUMN eg.comprehendId IS 'Comprehend Identifier';
COMMENT ON COLUMN eg.studyid IS 'Study Identifier';
COMMENT ON COLUMN eg.siteid IS 'Site Identifier';
COMMENT ON COLUMN eg.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN eg.egseq IS 'ECG Sequence Number';
COMMENT ON COLUMN eg.egtestcd IS 'ECG Test or Examination Short Name';
COMMENT ON COLUMN eg.egtest IS 'ECG Test or Examination Name';
COMMENT ON COLUMN eg.egcat IS 'Category for ECG';
COMMENT ON COLUMN eg.egscat IS 'Subcategory for ECG';
COMMENT ON COLUMN eg.egpos IS 'ECG Position of Subject';
COMMENT ON COLUMN eg.egorres IS 'Result/Finding in Original Units';
COMMENT ON COLUMN eg.egorresu IS 'Original Units';
COMMENT ON COLUMN eg.egstresn IS 'Numeric Result/Finding in Standard Units';
COMMENT ON COLUMN eg.egstresu IS 'Standard Units';
COMMENT ON COLUMN eg.egstat IS 'Completion Status';
COMMENT ON COLUMN eg.egloc IS 'Lead Location User for Measurement';
COMMENT ON COLUMN eg.egblfl IS 'Baseline Flag';
COMMENT ON COLUMN eg.visit IS 'Visit Name';
COMMENT ON COLUMN eg.egdtc IS 'Date/Time of ECG';
COMMENT ON COLUMN eg.egtm IS 'Time of Measurement';
COMMENT ON COLUMN eg.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN eg.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE pe IS 'Physical Examination';
COMMENT ON COLUMN pe.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN pe.studyid IS 'Study Identifier';
COMMENT ON COLUMN pe.siteid IS 'Site Identifier';
COMMENT ON COLUMN pe.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN pe.peseq IS 'Physical Examination Sequence Number';
COMMENT ON COLUMN pe.petestcd IS 'Body System Examined Short Name';
COMMENT ON COLUMN pe.petest IS 'Body System Examined';
COMMENT ON COLUMN pe.pecat IS 'Category for Examination';
COMMENT ON COLUMN pe.pescat IS 'Subcategory for Examination';
COMMENT ON COLUMN pe.pebodsys IS 'Body System of Organ Class';
COMMENT ON COLUMN pe.peorres IS 'Verbatim Examination Finding';
COMMENT ON COLUMN pe.peorresu IS 'Original Units';
COMMENT ON COLUMN pe.pestat IS 'Completion Status';
COMMENT ON COLUMN pe.peloc IS 'Location of Physical Exam Finding';
COMMENT ON COLUMN pe.visit IS 'Visit Name';
COMMENT ON COLUMN pe.pedtc IS 'Date/Time of Examination';
COMMENT ON COLUMN pe.petm IS 'Time of Examination';
COMMENT ON COLUMN pe.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN pe.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE flexField  IS 'Flex Field';
COMMENT ON COLUMN flexField.tableName IS 'Reference Table';
COMMENT ON COLUMN flexField.comprehendIdRef IS 'Reference Comprehend Identifier';
COMMENT ON COLUMN flexField.objectUniqueKeyRef IS 'Reference Object Unique Key';
COMMENT ON COLUMN flexField.studyid IS 'Study Identifier';
COMMENT ON COLUMN flexField.siteid IS 'Site Identifier';
COMMENT ON COLUMN flexField.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN flexField.flexName  IS 'Name';
COMMENT ON COLUMN flexField.flexLabel  IS 'Label';
COMMENT ON COLUMN flexField.flexValue  IS 'Value';
COMMENT ON COLUMN flexField.flexValueDtc IS 'Value Date';
COMMENT ON COLUMN flexField.flexValueTime IS 'Value Time';
COMMENT ON COLUMN flexField.flexOrder IS 'Sort Order Value';
COMMENT ON COLUMN flexField.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rslt IS 'Test or Examination Results';
COMMENT ON COLUMN rslt.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rslt.studyid IS 'Study Identifier';
COMMENT ON COLUMN rslt.siteid IS 'Site Identifier';
COMMENT ON COLUMN rslt.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rslt.visitnum  IS 'Visit Number';
COMMENT ON COLUMN rslt.visit  IS 'Visit';
COMMENT ON COLUMN rslt.rsltdtc  IS 'Test or Examination Start Date';
COMMENT ON COLUMN rslt.rslttm IS 'Test or Examination Start Time';
COMMENT ON COLUMN rslt.rsltdy IS 'Test or Examination Start Study Day';
COMMENT ON COLUMN rslt.rsltseq IS 'Test or Examination Sequence Number';
COMMENT ON COLUMN rslt.resulttype IS 'Result Type';
COMMENT ON COLUMN rslt.rshttestcd IS 'Result Short Name';
COMMENT ON COLUMN rslt.rslttest IS 'Test or Examination Name';
COMMENT ON COLUMN rslt.rsltcat IS 'Result Category';
COMMENT ON COLUMN rslt.rlstscat IS 'Result Subcategory';
COMMENT ON COLUMN rslt.rlstorres IS 'Result or Finding Original Units';
COMMENT ON COLUMN rslt.rsltorresu IS 'Original Units';
COMMENT ON COLUMN rslt.rsltstresc IS 'Character Result or Finding Standard Format';
COMMENT ON COLUMN rslt.rsltstresu IS 'Standard Units';
COMMENT ON COLUMN rslt.rsltmethod IS 'Test or Examination Method';
COMMENT ON COLUMN rslt.tableref IS 'Reference Usdm Table';
COMMENT ON COLUMN rslt.objectuniquekeyref IS 'References Unique Key';
COMMENT ON COLUMN rslt.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN rslt.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE sitemonitoringvisitreport IS 'Site Monitoring Visit Reports';
COMMENT ON COLUMN sitemonitoringvisitreport.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN sitemonitoringvisitreport.studyid IS 'Study Identifier';
COMMENT ON COLUMN sitemonitoringvisitreport.siteid IS 'Site Identifier';
COMMENT ON COLUMN sitemonitoringvisitreport.siteName IS 'Site Name';
COMMENT ON COLUMN sitemonitoringvisitreport.investigatorname IS 'Site Investigator Name';
COMMENT ON COLUMN sitemonitoringvisitreport.subjectsenrolled IS 'Count of Enrolled Subjects';
COMMENT ON COLUMN sitemonitoringvisitreport.visitName IS 'Visit Name';
COMMENT ON COLUMN sitemonitoringvisitreport.visitcompleteddate IS 'Visit Completed Date';
COMMENT ON COLUMN sitemonitoringvisitreport.effort IS 'Time Effort for Site Monitoring Visit';
COMMENT ON COLUMN sitemonitoringvisitreport.effortunit IS 'Effort Unit of Measurement';
COMMENT ON COLUMN sitemonitoringvisitreport.craname IS 'CRA Name';
COMMENT ON COLUMN sitemonitoringvisitreport.comonitor IS 'Co-Monitor Name';
COMMENT ON COLUMN sitemonitoringvisitreport.approvername IS 'Approver Name';
COMMENT ON COLUMN sitemonitoringvisitreport.reporttype IS 'Report Type';
COMMENT ON COLUMN sitemonitoringvisitreport.firstsubmissiondate IS 'Report First Submitted Date';
COMMENT ON COLUMN sitemonitoringvisitreport.firstsubmissioncompleteddays IS 'Number Of Days After Report First Submission Completed';
COMMENT ON COLUMN sitemonitoringvisitreport.revisioncount IS 'Report Revision Count';
COMMENT ON COLUMN sitemonitoringvisitreport.finalapprovaldate IS 'Report Final Approval Date';
COMMENT ON COLUMN sitemonitoringvisitreport.finalapprovalcompleteddays IS 'Number Of Days After Report Final Approval Completed';
COMMENT ON COLUMN sitemonitoringvisitreport.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN sitemonitoringvisitreport.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE comprehendcustommetric IS 'Custom metrics';
COMMENT ON COLUMN comprehendcustommetric.metricid IS 'Metric Identifier';
COMMENT ON COLUMN comprehendcustommetric.studyid IS 'Study Identifier';
COMMENT ON COLUMN comprehendcustommetric.siteid IS 'Site Identifier';
COMMENT ON COLUMN comprehendcustommetric.numerator IS 'Metric Numerator';
COMMENT ON COLUMN comprehendcustommetric.denominator IS 'Metric Denominator';
COMMENT ON COLUMN comprehendcustommetric.invalidvalue IS 'Whether the metric value is invalid';
COMMENT ON COLUMN comprehendcustommetric.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE pc IS 'Pharmacokinetics Concentrations';
COMMENT ON COLUMN pc.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN pc.studyid IS 'Study Identifier';
COMMENT ON COLUMN pc.siteid IS 'Site Identifier';
COMMENT ON COLUMN pc.usubjid IS 'Unique Subject Identifier';
COMMENT ON COLUMN pc.pcseq IS 'Sequence Number';
COMMENT ON COLUMN pc.pctestcd IS 'Pharmacokinetic Test Short Name';
COMMENT ON COLUMN pc.pctest IS 'Pharmacokinetic Test Name';
COMMENT ON COLUMN pc.pcorres IS 'Result or Finding in Original Units';
COMMENT ON COLUMN pc.pcorresu IS 'Original Units';
COMMENT ON COLUMN pc.pcstresc IS 'Character Result/Finding in Standard Format';
COMMENT ON COLUMN pc.pcstresn IS 'Numeric Result/Finding in Standard Units';
COMMENT ON COLUMN pc.pcstresu IS 'Standard Units';
COMMENT ON COLUMN pc.pcnam IS 'Vendor Name';
COMMENT ON COLUMN pc.pcspec IS 'Specimen Material Type';
COMMENT ON COLUMN pc.pclloq IS 'Lower Limit of Quantitation';
COMMENT ON COLUMN pc.visitnum IS 'Visit Number';
COMMENT ON COLUMN pc.pcdtc IS 'Date/Time of Specimen Collection';
COMMENT ON COLUMN pc.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN pc.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE pp IS 'Pharmacokinetics Parameters';
COMMENT ON COLUMN pp.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN pp.studyid IS 'Study Identifier';
COMMENT ON COLUMN pp.siteid IS 'Site Identifier';
COMMENT ON COLUMN pp.usubjid IS 'Unique Subject Identifier';
COMMENT ON COLUMN pp.ppseq IS 'Sequence Number';
COMMENT ON COLUMN pp.pptestcd IS 'Parameter Short Name';
COMMENT ON COLUMN pp.pptest IS 'Parameter Name';
COMMENT ON COLUMN pp.ppcat IS 'Parameter Category';
COMMENT ON COLUMN pp.pporres IS 'Result or Finding in Original Units';
COMMENT ON COLUMN pp.pporresu IS 'Original Units';
COMMENT ON COLUMN pp.ppstresc IS 'Character Result/Finding in Standard Format';
COMMENT ON COLUMN pp.ppstresn IS 'Numeric Result/Finding in Standard Units';
COMMENT ON COLUMN pp.ppstresu IS 'Standard Units';
COMMENT ON COLUMN pp.ppspec IS 'Specimen Material Type';
COMMENT ON COLUMN pp.pprftdtc IS 'Date/Time of Reference Point';
COMMENT ON COLUMN pp.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN pp.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE tsdv IS 'Targeted Source Data Verification';
COMMENT ON COLUMN tsdv.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN tsdv.studyid IS 'Study Identifier';
COMMENT ON COLUMN tsdv.sdvtier IS 'Source Data Verification Tier';
COMMENT ON COLUMN tsdv.formid IS 'Form Identifier';
COMMENT ON COLUMN tsdv.fieldid IS 'Field Identifier';
COMMENT ON COLUMN tsdv.visit IS 'Visit Name';
COMMENT ON COLUMN tsdv.issdv IS 'Is Source Data Verification Required?';
COMMENT ON COLUMN tsdv.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN tsdv.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE dq_audit IS 'Data Quality Rules Audit';
COMMENT ON COLUMN dq_audit.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN dq_audit.customer_name IS 'Customer Name';
COMMENT ON COLUMN dq_audit.studyid IS 'Study Identifier';
COMMENT ON COLUMN dq_audit.source_system IS 'Study Source System';
COMMENT ON COLUMN dq_audit.dq_start_timestamp IS 'Data Quality Rule Start Timestamp';
COMMENT ON COLUMN dq_audit.src_schema IS 'Schema Name';
COMMENT ON COLUMN dq_audit.src_table IS 'Table Name';
COMMENT ON COLUMN dq_audit.record_count IS 'Record or Severity Count';
COMMENT ON COLUMN dq_audit.record_type IS 'Record or Severity Type';
COMMENT ON COLUMN dq_audit.dq_run_id IS 'DQ Unique Run ID';
COMMENT ON COLUMN dq_audit.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN dq_audit.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE dq_bad_data IS 'Data Quality Rules Bad Data';
COMMENT ON COLUMN dq_bad_data.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN dq_bad_data.src_rec IS 'Record from Source Table';
COMMENT ON COLUMN dq_bad_data.src_col_name IS 'Column Name of Source Table';
COMMENT ON COLUMN dq_bad_data.src_col_val IS 'Column Value of Source Table';
COMMENT ON COLUMN dq_bad_data.error_reason IS 'Error Reason';
COMMENT ON COLUMN dq_bad_data.severity IS 'Severity of Bad Record';
COMMENT ON COLUMN dq_bad_data.rule_type IS 'DQ Rule Type';
COMMENT ON COLUMN dq_bad_data.customer_name IS 'Customer Name';
COMMENT ON COLUMN dq_bad_data.studyid IS 'Study Identifier';
COMMENT ON COLUMN dq_bad_data.source_system IS 'Study Source System';
COMMENT ON COLUMN dq_bad_data.src_schema IS 'Schema Name';
COMMENT ON COLUMN dq_bad_data.src_table IS 'Table Name';
COMMENT ON COLUMN dq_bad_data.dq_start_timestamp IS 'Data Quality Rule Start Timestamp';
COMMENT ON COLUMN dq_bad_data.dq_run_id IS 'DQ Unique Run ID';
COMMENT ON COLUMN dq_bad_data.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN dq_bad_data.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE tva IS 'Trial Visits per Arm';
COMMENT ON COLUMN tva.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN tva.studyid IS 'Study Identifier';
COMMENT ON COLUMN tva.armcd IS 'Planned Arm Code';
COMMENT ON COLUMN tva.arm IS 'Description of Planned Arm';
COMMENT ON COLUMN tva.visitid IS 'Internal Identifier from EDC Source System';
COMMENT ON COLUMN tva.visitname IS 'Visit Display Name ( Mnemonic / Visit Name)';
COMMENT ON COLUMN tva.visitnum IS 'Visit Number';
COMMENT ON COLUMN tva.visitdy IS 'Target Day';
COMMENT ON COLUMN tva.visitwindowbefore IS 'Before Window';
COMMENT ON COLUMN tva.visitwindowafter IS 'After Window';
COMMENT ON COLUMN tva.visit_bl IS 'Baseline Visit';
COMMENT ON COLUMN tva.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN tva.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE se IS 'Subject Elements';
COMMENT ON COLUMN se.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN se.studyid IS 'Study Identifier';
COMMENT ON COLUMN se.siteid IS 'Site Identifier';
COMMENT ON COLUMN se.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN se.seseq IS 'Sequence Number';
COMMENT ON COLUMN se.etcd IS 'Element Code';
COMMENT ON COLUMN se.element IS 'Description of Element';
COMMENT ON COLUMN se.taetord IS 'Planned Order of Element within Arm';
COMMENT ON COLUMN se.epoch IS 'Epoch';
COMMENT ON COLUMN se.sestdtc IS 'Start Date/Time of Element (ISO)';
COMMENT ON COLUMN se.sestdat IS 'Start Date/Time of Element';
COMMENT ON COLUMN se.seendtc IS 'End Date/Time of Element (ISO)';
COMMENT ON COLUMN se.seendat IS 'End Date/Time of Element';
COMMENT ON COLUMN se.seupdes IS 'Description of Unplanned Element';
COMMENT ON COLUMN se.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN se.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE ta is 'Trial Arms';
COMMENT ON COLUMN ta.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN ta.studyid IS 'Study Identifier';
COMMENT ON COLUMN ta.armcd IS 'Planned Arm Code';
COMMENT ON COLUMN ta.arm IS 'Description of Planned Arm';
COMMENT ON COLUMN ta.taetord IS 'Planned Order of Element within Arm';
COMMENT ON COLUMN ta.etcd IS 'Element Code';
COMMENT ON COLUMN ta.element IS 'Description of Element';
COMMENT ON COLUMN ta.tabranch IS 'Branch';
COMMENT ON COLUMN ta.tatrans IS 'Transition Rule';
COMMENT ON COLUMN ta.epoch IS 'Epoch';
COMMENT ON COLUMN ta.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN ta.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE te is 'Trial Elements';
COMMENT ON COLUMN te.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN te.studyid IS 'Study Identifier';
COMMENT ON COLUMN te.etcd IS 'Element Code';
COMMENT ON COLUMN te.element IS 'Description of Element';
COMMENT ON COLUMN te.testrl IS 'Rule for Start of Element';
COMMENT ON COLUMN te.teenrl IS 'Rule for End of Element';
COMMENT ON COLUMN te.tedur IS 'Planned Duration of Element';
COMMENT ON COLUMN te.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN te.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE siteexpendituredata is 'Expense Details per Site';
COMMENT ON COLUMN siteexpendituredata.comprehendid is 'Comprehend Identifier';
COMMENT ON COLUMN siteexpendituredata.studyid is 'Study Identifier';
COMMENT ON COLUMN siteexpendituredata.sitecountry is 'Site Country';
COMMENT ON COLUMN siteexpendituredata.siteid is 'Site Identifier';
COMMENT ON COLUMN siteexpendituredata.usubjid is 'Subject Identifier';
COMMENT ON COLUMN siteexpendituredata.event_category_id is 'Cost Category Identifier';
COMMENT ON COLUMN siteexpendituredata.event_category_name is 'Cost Category Name';
COMMENT ON COLUMN siteexpendituredata.event_subcategory_id is 'Cost Subcategory Identifier';
COMMENT ON COLUMN siteexpendituredata.event_subcategory_name is 'Cost Subcategory Name';
COMMENT ON COLUMN siteexpendituredata.cost_incurred_date is 'Date on which cost was incurred';
COMMENT ON COLUMN siteexpendituredata.cost_incurred_month is 'Month in which cost was incurred';
COMMENT ON COLUMN siteexpendituredata.cost_incurred_year is 'Year in which cost was incurred';
COMMENT ON COLUMN siteexpendituredata.costcurrency is 'Transaction Currency';
COMMENT ON COLUMN siteexpendituredata.currencybudgetamnt is 'Budget amount in country currency';
COMMENT ON COLUMN siteexpendituredata.currencyactualamnt is 'Actual cost amount in country currency';
COMMENT ON COLUMN siteexpendituredata.currencyforecastedamnt is 'Forecasted cost amount in country currency';
COMMENT ON COLUMN siteexpendituredata.usdbudgetamnt is 'Budget amount in USD';
COMMENT ON COLUMN siteexpendituredata.usdactualamnt is 'Actual cost amount in USD';
COMMENT ON COLUMN siteexpendituredata.usdforecastedamnt is 'Forecasted cost amount in USD';
COMMENT ON COLUMN siteexpendituredata.payeename is 'Clinic or hospital that pays for the event or activity';
COMMENT ON COLUMN siteexpendituredata.payeestatus is 'Payment Status';
COMMENT ON COLUMN siteexpendituredata.paymentdate is 'Date on which payment was made';
COMMENT ON COLUMN siteexpendituredata.paymentmonth is 'Month in which payment was made';
COMMENT ON COLUMN siteexpendituredata.paymentyear is 'Year in which payment was made';
COMMENT ON COLUMN siteexpendituredata.currencypaidamnt is 'Amount paid by payee in country currency';
COMMENT ON COLUMN siteexpendituredata.usdpaidamnt is 'Amount paid by payee in USD (from src system)';
COMMENT ON COLUMN siteexpendituredata.join_helper is 'Join siteexpendituredata and siteexpendituresummary based on JOIN_HELPER column';
COMMENT ON COLUMN siteexpendituredata.objectuniquekey is 'Object Unique Key';
COMMENT ON COLUMN siteexpendituredata.comprehend_update_time is 'Comprehend Update Time';

COMMENT ON TABLE siteexpendituresummary is 'Summary of Expenses on a Site';
COMMENT ON COLUMN siteexpendituresummary.comprehendid is 'Comprehend Identifier';
COMMENT ON COLUMN siteexpendituresummary.studyid is 'Study Identifier';
COMMENT ON COLUMN siteexpendituresummary.sitecountry is 'Site Country';
COMMENT ON COLUMN siteexpendituresummary.siteid is 'Site Identifier';
COMMENT ON COLUMN siteexpendituresummary.subjects is 'Count of Subjects';
COMMENT ON COLUMN siteexpendituresummary.event_category_id is 'Cost Category Identifier';
COMMENT ON COLUMN siteexpendituresummary.event_category_name is 'Cost Category Name';
COMMENT ON COLUMN siteexpendituresummary.cost_incurred_date is 'Date on which cost was incurred';
COMMENT ON COLUMN siteexpendituresummary.cost_incurred_month is 'Month in which cost was incurred';
COMMENT ON COLUMN siteexpendituresummary.cost_incurred_quarter is 'Quarter in which cost was incurred';
COMMENT ON COLUMN siteexpendituresummary.cost_incurred_year is 'Year in which cost was incurred';
COMMENT ON COLUMN siteexpendituresummary.costcurrency is 'Transaction Currency';
COMMENT ON COLUMN siteexpendituresummary.currencycatplannedexp is 'Budget for a category';
COMMENT ON COLUMN siteexpendituresummary.currencycatactualexp is 'Actual Expenditure till date for a category';
COMMENT ON COLUMN siteexpendituresummary.currencycatforecastedexp is 'Forecasted budget for remaining period for a category';
COMMENT ON COLUMN siteexpendituresummary.usdcatplannedexp is 'Budget for a category in USD';
COMMENT ON COLUMN siteexpendituresummary.usdcatactualexp is 'Actual Expenditure till date for a category in USD';
COMMENT ON COLUMN siteexpendituresummary.usdcatforecastedexp is 'Forecasted budget for remaining period for a category in USD';
COMMENT ON COLUMN siteexpendituresummary.join_helper is 'Join siteexpendituredata and siteexpendituresummary based on JOIN_HELPER column';
COMMENT ON COLUMN siteexpendituresummary.objectuniquekey is 'Object Unique Key';
COMMENT ON COLUMN siteexpendituresummary.comprehend_update_time is 'Comprehend Update Time';

