-- Presentation Layer Object Comments
-- NOTE: Please add to this file in alphabetical order
--
-- set search_path to cqs;

-- Data Field Listing (rpttab_fielddata)
COMMENT ON TABLE rpttab_fielddata IS 'Data Field Listing';
COMMENT ON COLUMN rpttab_fielddata.comprehendId IS 'Comprehend Identifier (studyid)';
COMMENT ON COLUMN rpttab_fielddata.sdvtier IS 'Source Document Verification Tier';
COMMENT ON COLUMN rpttab_fielddata.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpttab_fielddata.studyname IS 'Study Name';
COMMENT ON COLUMN rpttab_fielddata.istsdv IS 'Is Targeted Source Data Verification Enabled?';
COMMENT ON COLUMN rpttab_fielddata.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpttab_fielddata.sitename IS 'Site Name';
COMMENT ON COLUMN rpttab_fielddata.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpttab_fielddata.siteregion IS 'Site Region';
COMMENT ON COLUMN rpttab_fielddata.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpttab_fielddata.visitseq IS 'Visit Sequence';
COMMENT ON COLUMN rpttab_fielddata.visitnum IS 'Visit Number';
COMMENT ON COLUMN rpttab_fielddata.visit IS 'Visit';
COMMENT ON COLUMN rpttab_fielddata.svstdtc IS 'Subject Visit Start Date';
COMMENT ON COLUMN rpttab_fielddata.formid IS 'Form Identifier';
COMMENT ON COLUMN rpttab_fielddata.formname IS 'Form Name';
COMMENT ON COLUMN rpttab_fielddata.fieldid IS 'Field Identifier';
COMMENT ON COLUMN rpttab_fielddata.fieldname IS 'Field Name';
COMMENT ON COLUMN rpttab_fielddata.fieldseq IS 'Field Sequence';
COMMENT ON COLUMN rpttab_fielddata.datavalue IS 'Data Value';
COMMENT ON COLUMN rpttab_fielddata.dataentrydate IS 'Data Entry Date';
COMMENT ON COLUMN rpttab_fielddata.datacollecteddate IS 'Data Collected Date';
COMMENT ON COLUMN rpttab_fielddata.sdvdate IS 'SDV Date';
COMMENT ON COLUMN rpttab_fielddata.isprimaryendpoint IS 'Is Primary End Point?';
COMMENT ON COLUMN rpttab_fielddata.issecondaryendpoint IS 'Is Secondary End Point?';
COMMENT ON COLUMN rpttab_fielddata.isrequired IS 'Is Required?';
COMMENT ON COLUMN rpttab_fielddata.issdv IS 'Is SDV Required?';
COMMENT ON COLUMN rpttab_fielddata.rpt_custom_edge1 IS 'Custom Edge';
COMMENT ON COLUMN rpttab_fielddata.log_num IS 'Log Number';
COMMENT ON COLUMN rpttab_fielddata.comprehend_update_time IS 'Comprehend Update Time';

-- Subject with latest DS (rpt_latest_ds)
COMMENT ON TABLE rpt_latest_ds IS 'Subject Disposition with Latest Disposition Identified';
COMMENT ON COLUMN rpt_latest_ds.comprehendid IS 'Comprehend Identifier (studyid~siteid~usubjid)';
COMMENT ON COLUMN rpt_latest_ds.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN rpt_latest_ds.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_latest_ds.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_latest_ds.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_latest_ds.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_latest_ds.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_latest_ds.sitekey IS 'Site''s Comprehend Identifier (studyid~siteid)';
COMMENT ON COLUMN rpt_latest_ds.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_latest_ds.dsseq IS 'Subject Disposition Sequence (correlates to Category)';
COMMENT ON COLUMN rpt_latest_ds.dslabel IS 'Subject Disposition UI Label';
COMMENT ON COLUMN rpt_latest_ds.dscat IS 'Subject Disposition Category';
COMMENT ON COLUMN rpt_latest_ds.dsterm IS 'Subject Disposition Term';
COMMENT ON COLUMN rpt_latest_ds.dsstdtc_by_month IS 'Subject Disposition Event Date Truncated to Month';
COMMENT ON COLUMN rpt_latest_ds.dsscat IS 'Subject Disposition Sub-category (e.g. Reason)';
COMMENT ON COLUMN rpt_latest_ds.dsevent IS 'Subject Disposition Internal Event';
COMMENT ON COLUMN rpt_latest_ds.is_latest_ds IS 'Is this Subject Disposition the Latest for this Subject?';
COMMENT ON COLUMN rpt_latest_ds.dswithdrawn IS 'Is Subject Disposition Withdrawn?';
COMMENT ON COLUMN rpt_latest_ds.comprehend_update_time IS 'Comprehend Update Time';

-- Subject with latest DS (rpt_latest_ds)
COMMENT ON TABLE rpt_ds IS 'Subject Disposition with Disposition Over Time Period';
COMMENT ON COLUMN rpt_ds.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_ds.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_ds.program IS 'Program';
COMMENT ON COLUMN rpt_ds.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_ds.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_ds.sitecro IS 'Site Contract Research Organization (CRO)';
COMMENT ON COLUMN rpt_ds.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_ds.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_ds.dsseq IS 'Subject Disposition Sequence (correlates to Category)';
COMMENT ON COLUMN rpt_ds.dscat IS 'Subject Disposition Category';
COMMENT ON COLUMN rpt_ds.dsterm IS 'Subject Disposition Term';
COMMENT ON COLUMN rpt_ds.period_starting_date IS 'Subject Disposition Period Start Date';
COMMENT ON COLUMN rpt_ds.period_ending_date IS 'Subject Disposition Period End Date';
COMMENT ON COLUMN rpt_ds.ds_count IS 'Subject Disposition Count for Each Period';
COMMENT ON COLUMN rpt_ds.ds_cumulative_count IS 'Subject Disposition Cumulative Count ';
COMMENT ON COLUMN rpt_ds.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_data_entry IS 'Data Entry Rate Presentation Table';
COMMENT ON COLUMN rpt_data_entry.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_data_entry.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_data_entry.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_data_entry.trunc_month IS 'Form Data Collected Date (Month)';
COMMENT ON COLUMN rpt_data_entry.avg_days_in_month_interval IS 'Average Duration (days) Between Form Data Collected Date and Data Entry Date per SubjectMonth';
COMMENT ON COLUMN rpt_data_entry.forms_in_month_interval IS 'Count of Forms by Data Collected Date per SubjectMonth';
COMMENT ON COLUMN rpt_data_entry.study_average IS 'Average Duration (days) Between Form Data Collected Date and Data Entry Date per Study';
COMMENT ON COLUMN rpt_data_entry.avg_entry_days_on_interval IS 'Average Duration (days) Between Form Data Collected Date and Data Entry Date per Subject';
COMMENT ON COLUMN rpt_data_entry.forms_on_interval IS 'Count of Forms by Data Collected Date per Subject';
COMMENT ON COLUMN rpt_data_entry.isprimaryendpoint IS 'Counts Only Include Primary Endpoint Forms?';
COMMENT ON COLUMN rpt_data_entry.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_ae_rate_by_subject_days IS 'Adverse Event Rate by Subject Days';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.aestdtc IS 'Adverse Event Start Date';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.aeseq IS 'Adverse Event Sequence';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.aeterm IS 'Adverse Event Primary Term';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.aeser IS 'Serious (e.g. Serious, Non-Serious, Unknown)';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.aerelnst IS 'Is AE Related to the DrugDevice? (e.g. Yes, No, or Unknown)';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.category IS 'Adverse Event Category';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.month_trunc IS 'Adverse Event Start Month';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.subject_day_this_month IS 'Subject Days Active this Month';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.study_subjects IS 'Total Number of Subjects per Study';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.study_total_subject_days_this_category IS 'Total Subject Days Across the Study';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.study_total_ae_count_this_category IS 'Total Adverse Event Count';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.objectuniquekey IS 'Unique Edge Key';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.weight IS 'Adverse Event Weight';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.subject_days_weight_ratio IS 'Adverse Event Subject Days/Weight Ratio';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_subject_visit_schedule IS 'Subject Visit Schedule Compliance Presentation View';
COMMENT ON COLUMN rpt_subject_visit_schedule.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_subject_visit_schedule.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_subject_visit_schedule.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_subject_visit_schedule.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_subject_visit_schedule.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_subject_visit_schedule.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_subject_visit_schedule.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_subject_visit_schedule.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_subject_visit_schedule.visit IS 'Visit';
COMMENT ON COLUMN rpt_subject_visit_schedule.visitnum IS 'Visit Number';
COMMENT ON COLUMN rpt_subject_visit_schedule.visitdy IS 'Visit Day (from start of study)';
COMMENT ON COLUMN rpt_subject_visit_schedule.visitwindowbefore IS 'Acceptable Visit Window Before Visit Day (in days)';
COMMENT ON COLUMN rpt_subject_visit_schedule.visitwindowafter IS 'Acceptable Visit Window After Visit Day (in days)';
COMMENT ON COLUMN rpt_subject_visit_schedule.first_visit IS 'Start Date of First Visit';
COMMENT ON COLUMN rpt_subject_visit_schedule.svmod_visitnum IS 'Most Recent Visit Number';
COMMENT ON COLUMN rpt_subject_visit_schedule.svmod_visit IS 'Most Recent Visit';
COMMENT ON COLUMN rpt_subject_visit_schedule.visit_start_dtc IS 'Visit Start Date';
COMMENT ON COLUMN rpt_subject_visit_schedule.visit_end_dtc IS 'Visit End Date';
COMMENT ON COLUMN rpt_subject_visit_schedule.visitseq IS 'Visit Sequence';
COMMENT ON COLUMN rpt_subject_visit_schedule.visitdy_rebase IS 'Offset calculation for visitdy when rebasing on previous visit';
COMMENT ON COLUMN rpt_subject_visit_schedule.visitdy_derived IS 'Derived visit day based on visitday rebase';
COMMENT ON COLUMN rpt_subject_visit_schedule.previous_visitdy IS 'Previous visit day or if that is null the current visit day';
COMMENT ON COLUMN rpt_subject_visit_schedule.previous_visit_start_dtc IS 'Previous visit start date or if that is null the first visit';
COMMENT ON COLUMN rpt_subject_visit_schedule.windowopen IS 'Window Open';
COMMENT ON COLUMN rpt_subject_visit_schedule.windowclosed IS 'Window Closed';
COMMENT ON COLUMN rpt_subject_visit_schedule.expected IS 'Expected Visit Flag';
COMMENT ON COLUMN rpt_subject_visit_schedule.visit_days IS 'Subject Visit Days from First Visit';
COMMENT ON COLUMN rpt_subject_visit_schedule.category IS 'Visit Compliance Category';
COMMENT ON COLUMN rpt_subject_visit_schedule.trunc_month IS 'Visit Start Month';
COMMENT ON COLUMN rpt_subject_visit_schedule.schedule_compliance IS 'Schedule Compliance';
COMMENT ON COLUMN rpt_subject_visit_schedule.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_subject_visit_schedule_last_visit IS 'Subject Visit Schedule (Last Visit)';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.visit IS 'Visit';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.visitnum IS 'Visit Number';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.visitdy IS 'Visit Day (from start of study)';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.visitwindowbefore IS 'Acceptable Visit Window Before Visit Day (in days)';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.visitwindowafter IS 'Acceptable Visit Window After Visit Day (in days)';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.first_visit IS 'Start Date of First Visit';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.windowopen IS 'Window Open';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.windowclosed IS 'Window Closed';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.svmod_visitnum IS 'Most Recent Visit Number';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.svmod_visit IS 'Most Recent Visit';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.visit_start_dtc IS 'Visit Start Date';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.visit_end_dtc IS 'Visit End Date';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.visitseq IS 'Visit Sequence';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.visit_days IS 'Subject Visit Days from First Visit';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.trunc_month IS 'Visit Start Month';
COMMENT ON COLUMN rpt_subject_visit_schedule_last_visit.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_query_rate_by_subject_days IS 'Query Rate by Subject Days';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.month IS 'Month';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.is_enrolled IS 'Subject is enrolled?';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.subject_days IS 'Subject Days';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.subject_days_cumulative IS 'Subject Days (Cumulative)';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.query_count IS 'Query Count';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.query_count_cumulative IS 'Query Count (Cumulative)';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.open_query_count IS 'Open Query Count at end of month';
COMMENT ON COLUMN rpt_query_rate_by_subject_days.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_query_rate_by_ecrf IS 'Query Rate by eCRF';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.formid IS 'Form Identifier';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.is_enrolled IS 'Subject is enrolled?';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.formname IS 'Form Name';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.form_count IS 'Collected eCRF Count';
COMMENT ON COLUMN rpt_query_rate_by_ecrf.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_ip_accountability IS 'IP Accountability Presentation Table';
COMMENT ON COLUMN rpt_ip_accountability.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_ip_accountability.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_ip_accountability.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_ip_accountability.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_ip_accountability.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_ip_accountability.trunc_ip_month IS 'Truncated Month of drugaccountability.date';
COMMENT ON COLUMN rpt_ip_accountability.shipped IS 'Shipped Count';
COMMENT ON COLUMN rpt_ip_accountability.received IS 'Received Count';
COMMENT ON COLUMN rpt_ip_accountability.lost_in_transit IS 'Lost in Transit ';
COMMENT ON COLUMN rpt_ip_accountability.lost_at_site IS 'Lost at Site';
COMMENT ON COLUMN rpt_ip_accountability.dispensed IS 'Dispensed';
COMMENT ON COLUMN rpt_ip_accountability.returned_to_site IS 'Returned to Site';
COMMENT ON COLUMN rpt_ip_accountability.returned_to_distribution IS 'Returned to Distribution';
COMMENT ON COLUMN rpt_ip_accountability.avg_shipped IS 'Averged Shipped per StudySite';
COMMENT ON COLUMN rpt_ip_accountability.avg_received IS 'Averged Received per StudySite';
COMMENT ON COLUMN rpt_ip_accountability.avg_lost_in_transit IS 'Study Averge Lost in Transit';
COMMENT ON COLUMN rpt_ip_accountability.avg_lost_at_site IS 'Study Average Lost at Site';
COMMENT ON COLUMN rpt_ip_accountability.avg_dispensed IS 'Study Average Dispensed per Site';
COMMENT ON COLUMN rpt_ip_accountability.avg_returned_to_site IS 'Study Average Returned per Site';
COMMENT ON COLUMN rpt_ip_accountability.avg_returned_to_distribution IS 'Study Averge Returned to Distribution per Site';
COMMENT ON COLUMN rpt_ip_accountability.total_enrolled_per_study IS 'Study Total Enrolled';
COMMENT ON COLUMN rpt_ip_accountability.subjects_enrolled_at_site IS 'Site Total Enrollment';
COMMENT ON COLUMN rpt_ip_accountability.subjects_enrolled_at_country IS 'Country Total Enrollment';
COMMENT ON COLUMN rpt_ip_accountability.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_ae_rel_week IS 'Adverse Events by Relative Trial Week';
COMMENT ON COLUMN rpt_ae_rel_week.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_ae_rel_week.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_ae_rel_week.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_ae_rel_week.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_ae_rel_week.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_ae_rel_week.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_ae_rel_week.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_ae_rel_week.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_ae_rel_week.aeterm IS 'Adverse Event Primary Term';
COMMENT ON COLUMN rpt_ae_rel_week.aeseq IS 'Adverse Event Sequence Number';
COMMENT ON COLUMN rpt_ae_rel_week.aestdtc IS 'Adverse Event Start Date';
COMMENT ON COLUMN rpt_ae_rel_week.dsstdtc IS 'Subject Enrollment Date';
COMMENT ON COLUMN rpt_ae_rel_week.relative_trial_week IS 'Relative Week (AE Start Date - Subject Enrollment Date)';
COMMENT ON COLUMN rpt_ae_rel_week.objectuniquekey IS 'Unique edge to CCDM AE';
COMMENT ON COLUMN rpt_ae_rel_week.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_view_subj_count_by_last_visit IS 'Subjects By Latest Scheduled Visit';
COMMENT ON COLUMN rpt_view_subj_count_by_last_visit.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_view_subj_count_by_last_visit.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_view_subj_count_by_last_visit.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_view_subj_count_by_last_visit.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_view_subj_count_by_last_visit.visit IS 'latest scheduled visit for this subject';
COMMENT ON COLUMN rpt_view_subj_count_by_last_visit.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_ae_study_baseline IS 'Study AE Baseline Presentation Table';
COMMENT ON COLUMN rpt_ae_study_baseline.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_ae_study_baseline.studyid IS 'Study Id';
COMMENT ON COLUMN rpt_ae_study_baseline.aeterm IS 'Adverse Event Primary Term';
COMMENT ON COLUMN rpt_ae_study_baseline.aeendtc IS 'Adverse Event End Date';
COMMENT ON COLUMN rpt_ae_study_baseline.aestdtc IS 'Adverse Event Start Date';
COMMENT ON COLUMN rpt_ae_study_baseline.duration IS 'Adverse Event Duration (seconds)';
COMMENT ON COLUMN rpt_ae_study_baseline.study_avg_duration_this_term IS 'average duration across study for this term';
COMMENT ON COLUMN rpt_ae_study_baseline.study_count_this_term IS 'total count for the study this term';
COMMENT ON COLUMN rpt_ae_study_baseline.study_avg_duration_all_term IS 'average duration across study for all term';
COMMENT ON COLUMN rpt_ae_study_baseline.study_count_all_term IS 'total count for the study all term';
COMMENT ON COLUMN rpt_ae_study_baseline.avg_term_count IS 'count all terms  count(unique term)  for the study';
COMMENT ON COLUMN rpt_ae_study_baseline.objectuniquekey IS 'Unique edge to CCDM AE';
COMMENT ON COLUMN rpt_ae_study_baseline.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_open_query_age IS 'Open Queries by Age';
COMMENT ON COLUMN rpt_open_query_age.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_open_query_age.objectuniquekey IS 'Query Object Unique Key';
COMMENT ON COLUMN rpt_open_query_age.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_open_query_age.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_open_query_age.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_open_query_age.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_open_query_age.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_open_query_age.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_open_query_age.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_open_query_age.queryopendate_my IS 'Query Open Date in Month';
COMMENT ON COLUMN rpt_open_query_age.queryage IS 'Query Age (Today - Query Open Date)';
COMMENT ON COLUMN rpt_open_query_age.category IS 'Query Age Category Bucket';
COMMENT ON COLUMN rpt_open_query_age.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_missing_data IS 'Missing Field Data Presentation Table';
COMMENT ON COLUMN rpt_missing_data.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_missing_data.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_missing_data.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_missing_data.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_missing_data.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_missing_data.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_missing_data.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_missing_data.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_missing_data.formid IS 'Form Identifier';
COMMENT ON COLUMN rpt_missing_data.formname IS 'Form Name';
COMMENT ON COLUMN rpt_missing_data.visit IS 'Visit';
COMMENT ON COLUMN rpt_missing_data.visitseq IS 'Visit Sequence';
COMMENT ON COLUMN rpt_missing_data.visitnum IS 'Visit Number';
COMMENT ON COLUMN rpt_missing_data.svstdtc IS 'Visit Date';
COMMENT ON COLUMN rpt_missing_data.fieldid IS 'Field Identifier';
COMMENT ON COLUMN rpt_missing_data.fieldname IS 'Field Name';
COMMENT ON COLUMN rpt_missing_data.fieldseq IS 'Field Sequence';
COMMENT ON COLUMN rpt_missing_data.datavalue IS 'Data Value';
COMMENT ON COLUMN rpt_missing_data.dataentrydate IS 'Data Entry Date';
COMMENT ON COLUMN rpt_missing_data.datacollecteddate IS 'Data Collected Date';
COMMENT ON COLUMN rpt_missing_data.sdvdate IS 'SDV Date';
COMMENT ON COLUMN rpt_missing_data.issdv IS 'Is SDV?';
COMMENT ON COLUMN rpt_missing_data.isprimaryendpoint IS 'Is Primary Endpoint?';
COMMENT ON COLUMN rpt_missing_data.issecondaryendpoint IS 'Is Secondary Endpoint?';
COMMENT ON COLUMN rpt_missing_data.isrequired IS 'Is Required?';
COMMENT ON COLUMN rpt_missing_data.completed IS 'Completed?';
COMMENT ON COLUMN rpt_missing_data.log_num IS 'Log Number';
COMMENT ON COLUMN rpt_missing_data.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_monitoring_visit_record IS 'Site Monitoring Visit Record';
COMMENT ON COLUMN rpt_monitoring_visit_record.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_monitoring_visit_record.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_monitoring_visit_record.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_monitoring_visit_record.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_monitoring_visit_record.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_monitoring_visit_record.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_monitoring_visit_record.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_monitoring_visit_record.siteinvestigatorname IS 'Site Investigator Name';
COMMENT ON COLUMN rpt_monitoring_visit_record.sitecraname IS 'Site CRA Name';
COMMENT ON COLUMN rpt_monitoring_visit_record.visitname IS 'Visit Name';
COMMENT ON COLUMN rpt_monitoring_visit_record.visitdate IS 'Visit Date';
COMMENT ON COLUMN rpt_monitoring_visit_record.plannedvisitdate IS 'Planned Visit Date';
COMMENT ON COLUMN rpt_monitoring_visit_record.latevisitdays IS 'Late Visit Days';
COMMENT ON COLUMN rpt_monitoring_visit_record.visitseq IS 'Visit Sequence';
COMMENT ON COLUMN rpt_monitoring_visit_record.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_enrollment_analytics IS 'Enrollment Analytics Presentation Table';
COMMENT ON COLUMN  rpt_enrollment_analytics.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN  rpt_enrollment_analytics.therapeuticarea IS 'Therapeutic Area';
COMMENT ON COLUMN  rpt_enrollment_analytics.program IS 'Program';
COMMENT ON COLUMN  rpt_enrollment_analytics.studyid IS 'Study Identifier';
COMMENT ON COLUMN  rpt_enrollment_analytics.studyname IS 'Study Name';
COMMENT ON COLUMN  rpt_enrollment_analytics.studystartdate IS 'Study Start Date';
COMMENT ON COLUMN  rpt_enrollment_analytics.studycompletiondate IS 'Study Completion Date';
COMMENT ON COLUMN  rpt_enrollment_analytics.currentdate IS 'Current Date';
COMMENT ON COLUMN  rpt_enrollment_analytics.planned_fsi_date IS 'Planned First Subject In Date';
COMMENT ON COLUMN  rpt_enrollment_analytics.planned_lsi_date IS 'Planned Last Subject In Date';
COMMENT ON COLUMN  rpt_enrollment_analytics.planned_enrollment_days IS 'Planned Enrollment Days';
COMMENT ON COLUMN  rpt_enrollment_analytics.actual_fsi_date IS 'Actual First Subject In Date';
COMMENT ON COLUMN  rpt_enrollment_analytics.actual_lsi_date IS 'Actual Last Subject In Date';
COMMENT ON COLUMN  rpt_enrollment_analytics.actual_enrollment_days IS 'Actual Enrollment Days';
COMMENT ON COLUMN  rpt_enrollment_analytics.planned_enrollment_count IS 'Planned Enrollment Count';
COMMENT ON COLUMN  rpt_enrollment_analytics.actual_enrollment_count IS 'Actual Enrollment Count';
COMMENT ON COLUMN  rpt_enrollment_analytics.planned_enrollment_count_todate IS 'Planned Enrollment Count to date';
COMMENT ON COLUMN  rpt_enrollment_analytics.enrollment_status IS 'Enrollment Status';
COMMENT ON COLUMN  rpt_enrollment_analytics.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_resource_analytics IS 'Resource Analytics Presentation Table';
COMMENT ON COLUMN rpt_resource_analytics.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_resource_analytics.cro IS 'Contract Research Organization';
COMMENT ON COLUMN rpt_resource_analytics.therapeuticarea IS 'Study Therapeutic Area';
COMMENT ON COLUMN rpt_resource_analytics.program IS 'Study Program';
COMMENT ON COLUMN rpt_resource_analytics.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_resource_analytics.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_resource_analytics.cra_count IS 'Total Active CRAs';
COMMENT ON COLUMN rpt_resource_analytics.enrollment_count IS 'Total Enrolled';
COMMENT ON COLUMN rpt_resource_analytics.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_study_risk_analytics IS 'Study Risk Analytics Table';
COMMENT ON COLUMN rpt_study_risk_analytics.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_study_risk_analytics.cro IS 'Contract Research Organization';
COMMENT ON COLUMN rpt_study_risk_analytics.therapeuticarea IS 'Therapeutic Area';
COMMENT ON COLUMN rpt_study_risk_analytics.program IS 'Program';
COMMENT ON COLUMN rpt_study_risk_analytics.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_study_risk_analytics.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_study_risk_analytics.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_study_risk_analytics.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_study_risk_analytics.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_study_risk_analytics.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_study_risk_analytics.expected_pd_rate IS 'Expected Protocol Deviation Rate';
COMMENT ON COLUMN rpt_study_risk_analytics.expected_screen_failure_rate IS 'Expected Screen Failure Rate';
COMMENT ON COLUMN rpt_study_risk_analytics.expected_ae_rate IS 'Expected AE Rate';
COMMENT ON COLUMN rpt_study_risk_analytics.actual_pd_count IS 'Actual Protocol Deviation Count for Site';
COMMENT ON COLUMN rpt_study_risk_analytics.actual_screen_failure_count IS 'Actual Screen Failure Count for Site';
COMMENT ON COLUMN rpt_study_risk_analytics.actual_ae_count IS 'Actual AE Count for Site';
COMMENT ON COLUMN rpt_study_risk_analytics.actual_study_days IS 'Actual Study Days since Site FSI';
COMMENT ON COLUMN rpt_study_risk_analytics.enrollment_count IS 'Enrolled Subject Count for Site';
COMMENT ON COLUMN rpt_study_risk_analytics.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_expenditure_analytics IS 'Expenditure Analytics Presentation Table';
COMMENT ON COLUMN rpt_expenditure_analytics.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_expenditure_analytics.therapeuticarea IS 'Study Therapeutic Area';
COMMENT ON COLUMN rpt_expenditure_analytics.program IS 'Study Program';
COMMENT ON COLUMN rpt_expenditure_analytics.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_expenditure_analytics.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_expenditure_analytics.budget_month IS 'Budget Month';
COMMENT ON COLUMN rpt_expenditure_analytics.expenditure_units IS 'Expenditure Units';
COMMENT ON COLUMN rpt_expenditure_analytics.planned_expenditure IS 'Planned Expenditure Amount';
COMMENT ON COLUMN rpt_expenditure_analytics.actual_expenditure IS 'Actual Expenditure Amount';
COMMENT ON COLUMN rpt_expenditure_analytics.month_overbudget IS 'Amount Over Budget (Month)';
COMMENT ON COLUMN rpt_expenditure_analytics.total_budget IS 'Study Total Budget';
COMMENT ON COLUMN rpt_expenditure_analytics.total_spent IS 'Study Total Spent';
COMMENT ON COLUMN rpt_expenditure_analytics.total_budget_balance IS 'Study Total Budget Balance';
COMMENT ON COLUMN rpt_expenditure_analytics.total_overbudget IS 'Study Total Over Budget';
COMMENT ON COLUMN rpt_expenditure_analytics.total_budget_used_rate IS 'Study Rate of Total Budget Used';
COMMENT ON COLUMN rpt_expenditure_analytics.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_pivotal_study_analytics IS 'Pivotal Study Analytics Presentation Table';
COMMENT ON COLUMN rpt_pivotal_study_analytics.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_pivotal_study_analytics.therapeuticarea IS 'Study Therapeutic Area';
COMMENT ON COLUMN rpt_pivotal_study_analytics.program IS 'Study Program';
COMMENT ON COLUMN rpt_pivotal_study_analytics.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_pivotal_study_analytics.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_pivotal_study_analytics.studycronames IS 'Study CRO Names';
COMMENT ON COLUMN rpt_pivotal_study_analytics.previous_milestone_planned_date IS 'Previous Milestone Planned Date';
COMMENT ON COLUMN rpt_pivotal_study_analytics.previous_milestone_actual_completion_date IS 'Previous Milestone Actual Completion Date';
COMMENT ON COLUMN rpt_pivotal_study_analytics.current_milestone IS 'Current Milestone';
COMMENT ON COLUMN rpt_pivotal_study_analytics.current_milestone_planned_date IS 'Current Milestone Planned Date';
COMMENT ON COLUMN rpt_pivotal_study_analytics.current_milestone_projected_date IS 'Current Milestone Projected Date';
COMMENT ON COLUMN rpt_pivotal_study_analytics.milestone_achievement_status IS 'Milestone Achievement (On Plan or Behind Plan)';
COMMENT ON COLUMN rpt_pivotal_study_analytics.current_enrollment_count IS 'Current Enrollment Count';
COMMENT ON COLUMN rpt_pivotal_study_analytics.target_enrollment_count IS 'Target Enrollment Count';
COMMENT ON COLUMN rpt_pivotal_study_analytics.lsi_planned_date IS 'Planned Last Subject In Date';
COMMENT ON COLUMN rpt_pivotal_study_analytics.lsi_projected_date IS 'Projected Last Subject In Date';
COMMENT ON COLUMN rpt_pivotal_study_analytics.lsi_achievement_status IS 'Last Subject In Achievement Status (On Plan or Behind Plan)';
COMMENT ON COLUMN rpt_pivotal_study_analytics.current_site_activation_count IS 'Current Site Activation count';
COMMENT ON COLUMN rpt_pivotal_study_analytics.target_site_activation_count IS 'Target Site Activation count';
COMMENT ON COLUMN rpt_pivotal_study_analytics.site_activation_planned_date IS 'Planned Site Activation Complete Date';
COMMENT ON COLUMN rpt_pivotal_study_analytics.site_activation_projected_date IS 'Projected Site Activation Complete Date';
COMMENT ON COLUMN rpt_pivotal_study_analytics.site_activation_days_behind IS 'Site Activation Days Behind Plan';
COMMENT ON COLUMN rpt_pivotal_study_analytics.study_risk_level IS 'Study Risk Level (High, Medium, Low)';
COMMENT ON COLUMN rpt_pivotal_study_analytics.monte_carlo_optimistic_date IS 'Monte Carlo Optimistic Enrollment Forecast Date';
COMMENT ON COLUMN rpt_pivotal_study_analytics.monte_carlo_realistic_date IS 'Monte Carlo Realistic Enrollment Forecast Date';
COMMENT ON COLUMN rpt_pivotal_study_analytics.monte_carlo_pessimistic_date IS 'Monte Carlo Pessimistic Enrollment Forecast Date';
COMMENT ON COLUMN rpt_pivotal_study_analytics.study_planned_monitoring_visit_frequency IS 'Study Planned Monitoring Visit Frequency';
COMMENT ON COLUMN rpt_pivotal_study_analytics.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_pivotal_study_analytics_datapoints IS 'Pivotal Study Analytics Datapoints Table';
COMMENT ON COLUMN rpt_pivotal_study_analytics_datapoints.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_pivotal_study_analytics_datapoints.therapeuticarea IS 'Study Therapeutic Area';
COMMENT ON COLUMN rpt_pivotal_study_analytics_datapoints.program IS 'Study Program';
COMMENT ON COLUMN rpt_pivotal_study_analytics_datapoints.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_pivotal_study_analytics_datapoints.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_pivotal_study_analytics_datapoints.forecast_type IS 'Type Of Regression Used For Forecasting';
COMMENT ON COLUMN rpt_pivotal_study_analytics_datapoints.forecast_date IS 'Forecast Date';
COMMENT ON COLUMN rpt_pivotal_study_analytics_datapoints.forecast_count IS 'Forecast Target Count';
COMMENT ON COLUMN rpt_pivotal_study_analytics_datapoints.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_portfolio_oversight IS 'Portfolio Oversight Presentation Table';
COMMENT ON COLUMN rpt_portfolio_oversight.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_portfolio_oversight.cro IS 'Contract Research Organization';
COMMENT ON COLUMN rpt_portfolio_oversight.therapeuticarea IS 'Therapeutic Area';
COMMENT ON COLUMN rpt_portfolio_oversight.program IS 'Program';
COMMENT ON COLUMN rpt_portfolio_oversight.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_portfolio_oversight.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_portfolio_oversight.milestone_achievement_status IS 'Milestone Achievement (On Plan or Behind Plan)';
COMMENT ON COLUMN rpt_portfolio_oversight.enrollment_status IS 'Enrollment Status';
COMMENT ON COLUMN rpt_portfolio_oversight.budget_status IS 'Budget Status (Overrun, Under, or On Budget)';
COMMENT ON COLUMN rpt_portfolio_oversight.total_overbudget_amount IS 'Total Overbudget Amount';
COMMENT ON COLUMN rpt_portfolio_oversight.total_overbudget_unit IS 'Total Overbudget Unit';
COMMENT ON COLUMN rpt_portfolio_oversight.study_risk_level IS 'Study Risk Level (High, Medium, Low)';
COMMENT ON COLUMN rpt_portfolio_oversight.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_subject_information IS 'Subject Information';
COMMENT ON COLUMN rpt_subject_information.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_subject_information.sitecro IS 'Site CRO';
COMMENT ON COLUMN rpt_subject_information.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_subject_information.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_subject_information.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_subject_information.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_subject_information.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_subject_information.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_subject_information.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_subject_information.subject_status IS 'Subject Status';
COMMENT ON COLUMN rpt_subject_information.consent_date IS 'Subject Informed Consent Date';
COMMENT ON COLUMN rpt_subject_information.enrollment_date IS 'Subject Enrollment Date';
COMMENT ON COLUMN rpt_subject_information.subject_start_date IS 'Subject Start Date';
COMMENT ON COLUMN rpt_subject_information.exit_date IS 'Subject Exit Date';
COMMENT ON COLUMN rpt_subject_information.subject_days IS 'Subject Number of Study Days';
COMMENT ON COLUMN rpt_subject_information.prior_30day_subject_days IS 'Subject 30 Days Prior Date';
COMMENT ON COLUMN rpt_subject_information.ae_count IS 'Subject Current Count of AEs';
COMMENT ON COLUMN rpt_subject_information.prior_30day_ae_count IS 'Subject 30 Days Prior Count of AEs';
COMMENT ON COLUMN rpt_subject_information.dv_count IS 'Subject Current Count of Deviations';
COMMENT ON COLUMN rpt_subject_information.prior_30day_dv_count IS 'Subject 30 Days Prior Count of Deviations';
COMMENT ON COLUMN rpt_subject_information.subject_day_start IS 'Subject Study Start Date';
COMMENT ON COLUMN rpt_subject_information.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpttab_dv IS 'Deviation Tabular Listing.';
COMMENT ON COLUMN rpttab_dv.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpttab_dv.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpttab_dv.studyname IS 'Study Name';
COMMENT ON COLUMN rpttab_dv.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpttab_dv.sitename IS 'Site Name';
COMMENT ON COLUMN rpttab_dv.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpttab_dv.siteregion IS 'Site Region';
COMMENT ON COLUMN rpttab_dv.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpttab_dv.visit IS 'Folder (aka Visit)';
COMMENT ON COLUMN rpttab_dv.formid IS 'Form';
COMMENT ON COLUMN rpttab_dv.dvcat IS 'Deviation Category';
COMMENT ON COLUMN rpttab_dv.dvseq IS 'Deviation Sequence Number';
COMMENT ON COLUMN rpttab_dv.dvterm IS 'Deviation Term';
COMMENT ON COLUMN rpttab_dv.dvstdtc IS 'Deviation Start Date';
COMMENT ON COLUMN rpttab_dv.dvendtc IS 'Deviation End Date';
COMMENT ON COLUMN rpttab_dv.dvscat IS 'Deviation Severity - Major or Minor';
COMMENT ON COLUMN rpttab_dv.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN rpttab_dv.dvstdtc_month IS 'Deviation Start Date - Month/Year';
COMMENT ON COLUMN rpttab_dv.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpttab_query IS 'Query Tabular Listing.';
COMMENT ON COLUMN rpttab_query.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpttab_query.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpttab_query.studyname IS 'Study Name';
COMMENT ON COLUMN rpttab_query.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpttab_query.sitename IS 'Site Name';
COMMENT ON COLUMN rpttab_query.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpttab_query.siteregion IS 'Site Region';
COMMENT ON COLUMN rpttab_query.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpttab_query.queryid IS 'Query Identifier';
COMMENT ON COLUMN rpttab_query.formid IS 'Query Page';
COMMENT ON COLUMN rpttab_query.fieldid IS 'Query Field';
COMMENT ON COLUMN rpttab_query.querytext IS 'Query Text';
COMMENT ON COLUMN rpttab_query.querytype IS 'Query Type';
COMMENT ON COLUMN rpttab_query.querystatus IS 'Query Status (Open, Answered, Closed)';
COMMENT ON COLUMN rpttab_query.queryopeneddate IS 'Query Open Date';
COMMENT ON COLUMN rpttab_query.queryresponsedate IS 'Query Response Date';
COMMENT ON COLUMN rpttab_query.querycloseddate IS 'Query Closed Date';
COMMENT ON COLUMN rpttab_query.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN rpttab_query.queryopeneddate_month IS 'Query Open Date - Month/Year';
COMMENT ON COLUMN rpttab_query.querycreator IS 'Query Creator';
COMMENT ON COLUMN rpttab_query.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_site_performance IS 'Site Performance Table';
COMMENT ON COLUMN rpt_site_performance.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_site_performance.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_site_performance.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_site_performance.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_site_performance.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_site_performance.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_site_performance.sitecro IS 'Site CRO';
COMMENT ON COLUMN rpt_site_performance.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_site_performance.sitecraname IS 'CRA Name';
COMMENT ON COLUMN rpt_site_performance.screen_failure_rate IS 'Screen Failure Rate';
COMMENT ON COLUMN rpt_site_performance.enrollment_rate IS 'Enrollment Rate';
COMMENT ON COLUMN rpt_site_performance.withdrawal_rate IS 'Withdrawal Rate';
COMMENT ON COLUMN rpt_site_performance.open_query_rate IS 'Open Query Rate';
COMMENT ON COLUMN rpt_site_performance.ae_rate IS 'AE Rate';
COMMENT ON COLUMN rpt_site_performance.pd_rate IS 'PD Rate';
COMMENT ON COLUMN rpt_site_performance.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_protocol_deviations_per_subject_per_visit IS 'Protocol Deviations per Subject Visit';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.studydescription IS 'Study Description';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.studystatus IS 'Study Status';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.studyphase IS 'Study Phase';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.studysponsor IS 'Study Sponsor';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.therapeuticarea IS 'Therapeutic Area';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.program IS 'Program';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.medicalindication IS 'Medical Indication';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.studystartdate IS 'Study Start Date';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.studycompletiondate IS 'Study Completion Date';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sitecro IS 'Site CRO';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.siteinvestigatorname IS 'Site Investigator Name';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sitecraname IS 'Site CRA Name';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sitecreationdate IS 'Site Creation Date';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.siteactivationdate IS 'Site Activation Date';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sitedeactivationdate IS 'Site Deactivation Date';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sortseq IS 'Sequence Number';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sv_visitnum IS 'Study Visit Number';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sv_visit IS 'Study Visit';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sv_visitseq IS 'Study Visit Sequence';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sv_svstdtc IS 'Study Visit Start Date';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sv_svendtc IS 'Study Visit End Date';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.sv_objectuniquekey IS 'Study Visit Object Unique Key';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.dv_dvseq IS 'Deviation Object Unique Key';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.dv_dvcat IS 'Deviation Category';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.dv_dvterm IS 'Deviation Term';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.dv_formid IS 'Deviation Form ID';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.dv_visit IS 'Deviation Visit';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.dv_dvstdtc IS 'Deviation Start Date';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.dv_dvendtc IS 'Deviation End Date';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.dv_dvscat IS 'Deviation Subcategory';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.dv_objectuniquekey IS 'Deviation Object Unique Key';
COMMENT ON COLUMN rpt_protocol_deviations_per_subject_per_visit.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_site_days IS 'Site Days Table';
COMMENT ON COLUMN rpt_site_days.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_site_days.siteid  IS 'Site Identifier';
COMMENT ON COLUMN rpt_site_days.studystartdate  IS 'Study Start Date';
COMMENT ON COLUMN rpt_site_days.studycompletiondate  IS 'Study Completion Date';
COMMENT ON COLUMN rpt_site_days.sitecreationdate  IS 'Site Creation Date';
COMMENT ON COLUMN rpt_site_days.siteactivationdate  IS 'Site Activation Date';
COMMENT ON COLUMN rpt_site_days.sitedaysenddt  IS 'Site Days End Date';
COMMENT ON COLUMN rpt_site_days.monthtrunc  IS 'Month';
COMMENT ON COLUMN rpt_site_days.site_days_count  IS 'Site Days Count for the Month';
COMMENT ON COLUMN rpt_site_days.site_days_cumulative  IS 'Site Days Count Cumulative';
COMMENT ON COLUMN rpt_site_days.comprehend_update_time  IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_pd_rate_by_subject_days IS 'Protocol Deviation Rate by Subject Days';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.sitecro IS 'Site Contract Research Organization (CRO)';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.visit IS 'Deviation Visit';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.formid IS 'Deviation Form Identifier';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.dvcat IS 'Deviation Category';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.dvterm IS 'Deviation Term';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.dvstdtc IS 'Deviation Start Date';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.dvendtc IS 'Deviation End Date';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.dvscat IS 'Deviation Severity';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.dvseq IS 'Deviation Sequence';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.weight IS 'Deviation Weight';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.subject_day_this_month IS 'Subject Days Active this Month';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.month_trunc IS 'Deviation Start Month';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_subject_days IS 'Subject Days Monthly Time Series';
COMMENT ON COLUMN rpt_subject_days.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_subject_days.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_subject_days.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_subject_days.studydescription IS 'Study Description';
COMMENT ON COLUMN rpt_subject_days.studystartdate IS 'Study Start Date';
COMMENT ON COLUMN rpt_subject_days.studycompletiondate IS 'Study Completion Date';
COMMENT ON COLUMN rpt_subject_days.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_subject_days.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_subject_days.sitecro IS 'Site Contract Research Organization (CRO)';
COMMENT ON COLUMN rpt_subject_days.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_subject_days.sitecreationdate IS 'Site Creation Date';
COMMENT ON COLUMN rpt_subject_days.siteactivationdate IS 'Site Activation Date';
COMMENT ON COLUMN rpt_subject_days.sitedeactivationdate IS 'Site Deactivation Date';
COMMENT ON COLUMN rpt_subject_days.siteinvestigatorname IS 'Site Investigator Name';
COMMENT ON COLUMN rpt_subject_days.sitecraname IS 'Site CRA Name';
COMMENT ON COLUMN rpt_subject_days.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_subject_days.subjectstatus IS 'Subject Status';
COMMENT ON COLUMN rpt_subject_days.exitdate IS 'Subject Exit Date';
COMMENT ON COLUMN rpt_subject_days.subjectstartdisposition IS 'Subject Start Disposition';
COMMENT ON COLUMN rpt_subject_days.subjectexitdisposition  IS 'Subject Exit Disposition';
COMMENT ON COLUMN rpt_subject_days.subjectdaystartdt IS 'Subject Days Start Date';
COMMENT ON COLUMN rpt_subject_days.subjectdaysenddt IS 'Subject Days End Date';
COMMENT ON COLUMN rpt_subject_days.thismonth IS 'Month';
COMMENT ON COLUMN rpt_subject_days.thismonthsubjectdays IS 'Subject Days';
COMMENT ON COLUMN rpt_subject_days.cumulativesubjectdays IS 'Subject Days Cumulative';
COMMENT ON COLUMN rpt_subject_days.totalsubjectdays IS 'Subject Days Total';
COMMENT ON COLUMN rpt_subject_days.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE dimdate IS 'Static Date Series';
COMMENT ON COLUMN dimdate.date_dim_id IS 'Static Date Identifier';
COMMENT ON COLUMN dimdate.date_actual IS 'Date Actual';
COMMENT ON COLUMN dimdate.epoch IS 'Epoch';
COMMENT ON COLUMN dimdate.day_suffix IS 'Day Suffix';
COMMENT ON COLUMN dimdate.day_name IS 'Day Name';
COMMENT ON COLUMN dimdate.day_of_week IS 'Day Of Week';
COMMENT ON COLUMN dimdate.day_of_month IS 'Day Of Month';
COMMENT ON COLUMN dimdate.day_of_quarter IS 'Day Of Quarter';
COMMENT ON COLUMN dimdate.day_of_year IS 'Day Of Year';
COMMENT ON COLUMN dimdate.week_of_month IS 'Week Of Month';
COMMENT ON COLUMN dimdate.week_of_year IS 'Week Of Year';
COMMENT ON COLUMN dimdate.week_of_year_iso IS 'Week Of Year ISO';
COMMENT ON COLUMN dimdate.month_actual IS 'Month Actual';
COMMENT ON COLUMN dimdate.month_name IS 'Month Name';
COMMENT ON COLUMN dimdate.month_name_abbreviated IS 'Month Name Abbreviated';
COMMENT ON COLUMN dimdate.quarter_actual IS 'Quarter Actual';
COMMENT ON COLUMN dimdate.quarter_name IS 'Quarter Name';
COMMENT ON COLUMN dimdate.year_actual IS 'Year Actual';
COMMENT ON COLUMN dimdate.first_day_of_week IS 'First Day Of Week';
COMMENT ON COLUMN dimdate.last_day_of_week IS 'Last Day Of Week';
COMMENT ON COLUMN dimdate.first_day_of_month IS 'First Day Of Month';
COMMENT ON COLUMN dimdate.last_day_of_month IS 'Last Day Of Month';
COMMENT ON COLUMN dimdate.first_day_of_quarter IS 'First Day Of Quarter';
COMMENT ON COLUMN dimdate.last_day_of_quarter IS 'Last Day Of Quarter';
COMMENT ON COLUMN dimdate.first_day_of_year IS 'First Day Of Year';
COMMENT ON COLUMN dimdate.last_day_of_year IS 'Last Day Of Year';
COMMENT ON COLUMN dimdate.mmyyyy IS 'Day with mmyyyy Format';
COMMENT ON COLUMN dimdate.mmddyyyy IS 'Day with mmddyyyy Format';
COMMENT ON COLUMN dimdate.weekend_indr IS 'Is Weekend';
COMMENT ON COLUMN dimdate.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE dimdisposition IS 'Subject Disposition Listing';
COMMENT ON COLUMN dimdisposition.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN dimdisposition.studyid IS 'Study Identifier';
COMMENT ON COLUMN dimdisposition.siteid IS 'Site Identifier';
COMMENT ON COLUMN dimdisposition.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN dimdisposition.dsseq IS 'Subject Disposition Sequence';
COMMENT ON COLUMN dimdisposition.dscat IS 'Subject Disposition Category';
COMMENT ON COLUMN dimdisposition.dsterm IS 'Subject Disposition Term';
COMMENT ON COLUMN dimdisposition.dsstdtc IS 'Subject Disposition Date';
COMMENT ON COLUMN dimdisposition.dsscat IS 'Subject Disposition Sub-category';
COMMENT ON COLUMN dimdisposition.dsevent IS 'Subject Disposition Internal Event';
COMMENT ON COLUMN dimdisposition.dsactive IS 'Is Subject Disposition Active?';
COMMENT ON COLUMN dimdisposition.dswithdrawn IS 'Is Subject Disposition Withdrawn?';
COMMENT ON COLUMN dimdisposition.dscompleted IS 'Is Subject Disposition Completed?';

COMMENT ON COLUMN dimdisposition.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN dimdisposition.dispositionmultiplier IS 'Disposition Multiplier';
COMMENT ON COLUMN dimdisposition.dispositiontype IS 'Disposition Type';
COMMENT ON COLUMN dimdisposition.islatestsequence IS 'Is Latest Sequence';
COMMENT ON COLUMN dimdisposition.subjectenrolled IS 'Subject Enrolled';
COMMENT ON COLUMN dimdisposition.subjectfailedscreen IS 'Subject Failed Screen';
COMMENT ON COLUMN dimdisposition.subjectscreened IS 'Subject Screened';
COMMENT ON COLUMN dimdisposition.subjectwithdrawn IS 'Subject Withdrawn';
COMMENT ON COLUMN dimdisposition.subjectconsented IS 'Subject Consented';
COMMENT ON COLUMN dimdisposition.subjectfailedrandomization IS 'Subject Failed Randomization';
COMMENT ON COLUMN dimdisposition.subjectevaluable IS 'Subject Evaluable';
COMMENT ON COLUMN dimdisposition.subjectconsentfailures IS 'Subject Consent Failures';
COMMENT ON COLUMN dimdisposition.subjectevaluablefailures IS 'Subject Evaluable Failures';
COMMENT ON COLUMN dimdisposition.subjectrandomized IS 'Subject Randomized';
COMMENT ON COLUMN dimdisposition.subjectcompleted IS 'Subject Completed';
COMMENT ON COLUMN dimdisposition.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE dimsite IS 'Site Listing';
COMMENT ON COLUMN dimsite.comprehendid IS 'Comprehend Identifier'; 
COMMENT ON COLUMN dimsite.siteid IS 'Site Identifier'; 
COMMENT ON COLUMN dimsite.studyid IS 'Study Identifier'; 
COMMENT ON COLUMN dimsite.sitename IS 'Site Name'; 
COMMENT ON COLUMN dimsite.croid IS 'Site Contract Research Organization Identifier (CRO)'; 
COMMENT ON COLUMN dimsite.sitecro IS 'Site Contract Research Organization (CRO)'; 
COMMENT ON COLUMN dimsite.siteinvestigatorname IS 'Site Investigator Name'; 
COMMENT ON COLUMN dimsite.sitecraname IS 'Site CRA Name'; 
COMMENT ON COLUMN dimsite.sitecountry IS 'Site Country'; 
COMMENT ON COLUMN dimsite.siteregion IS 'Site Region'; 
COMMENT ON COLUMN dimsite.sitecreationdate IS 'Site Creation Date'; 
COMMENT ON COLUMN dimsite.siteactivationdate IS 'Site Activation Date'; 
COMMENT ON COLUMN dimsite.sitedeactivationdate IS 'Site Deactivation Date'; 
COMMENT ON COLUMN dimsite.siteaddress1 IS 'Site Address Line 1'; 
COMMENT ON COLUMN dimsite.siteaddress2 IS 'Site Address Line 2'; 
COMMENT ON COLUMN dimsite.sitecity IS 'Site City'; 
COMMENT ON COLUMN dimsite.sitestate IS 'Site State'; 
COMMENT ON COLUMN dimsite.sitepostal IS 'Site Postal Code'; 
COMMENT ON COLUMN dimsite.site_subjects IS 'Count Of Subjects Per Site'; 
COMMENT ON COLUMN dimsite.subject_days IS 'Subject Days'; 
COMMENT ON COLUMN dimsite.subjects_screened_count IS 'Subjects Screened Count'; 
COMMENT ON COLUMN dimsite.failed_screen_count IS 'Failed Screen Count'; 
COMMENT ON COLUMN dimsite.site_active_days_count IS 'Site Active Days Count'; 
COMMENT ON COLUMN dimsite.enrolled_count IS 'Enrolled Count'; 
COMMENT ON COLUMN dimsite.withdrawn_count IS 'Withdrawn Count'; 
COMMENT ON COLUMN dimsite.open_query_count IS 'Open Query Count'; 
COMMENT ON COLUMN dimsite.ae_count IS 'AE Count'; 
COMMENT ON COLUMN dimsite.dv_count IS 'DV Count'; 
COMMENT ON COLUMN dimsite.subject_days_count IS 'Subject Days Count'; 
COMMENT ON COLUMN dimsite.screen_failure_rate IS 'Screen Failure Rate'; 
COMMENT ON COLUMN dimsite.enrollment_rate IS 'Enrollment Rate'; 
COMMENT ON COLUMN dimsite.withdrawal_rate IS 'Withdrawal Rate'; 
COMMENT ON COLUMN dimsite.open_query_rate IS 'Open Query Rate'; 
COMMENT ON COLUMN dimsite.ae_rate IS 'AE Rate'; 
COMMENT ON COLUMN dimsite.pd_rate IS 'PD Rate'; 
COMMENT ON COLUMN dimsite.sv_count IS 'Count Of Subject Visits Per Site'; 
COMMENT ON COLUMN dimsite.comprehend_update_time IS 'Comprehend Update Time'; 

COMMENT ON TABLE dimstudymilestone IS 'Study Milestone';
COMMENT ON COLUMN dimstudymilestone.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN dimstudymilestone.studyid IS 'Study Identifier';
COMMENT ON COLUMN dimstudymilestone.milestoneseq IS 'Milestone Sequence';
COMMENT ON COLUMN dimstudymilestone.milestonelabel IS 'Milestone Label';
COMMENT ON COLUMN dimstudymilestone.plannedstart IS 'Planned Start';
COMMENT ON COLUMN dimstudymilestone.plannedend IS 'Planned End';
COMMENT ON COLUMN dimstudymilestone.plannedduration IS 'Planned Duration';
COMMENT ON COLUMN dimstudymilestone.actualstart IS 'Actual Start';
COMMENT ON COLUMN dimstudymilestone.actualend IS 'Actual End';
COMMENT ON COLUMN dimstudymilestone.actualduration IS 'Actual Duration';
COMMENT ON COLUMN dimstudymilestone.delay IS 'Delay';
COMMENT ON COLUMN dimstudymilestone.expected_actual_end IS 'Expected Actual End';
COMMENT ON COLUMN dimstudymilestone.ismandatory IS 'Is Mandatory';
COMMENT ON COLUMN dimstudymilestone.iscriticalpath IS 'Is Critical Path';
COMMENT ON COLUMN dimstudymilestone.iscurrent IS 'Is Current';
COMMENT ON COLUMN dimstudymilestone.original_expected_date IS 'Original Expected Date';
COMMENT ON COLUMN dimstudymilestone.baseline_expected_date IS 'Baseline Expected Date';
COMMENT ON COLUMN dimstudymilestone.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE dimsubject IS 'Subject Listing';
COMMENT ON COLUMN dimsubject.siteid IS 'Site Identifier';
COMMENT ON COLUMN dimsubject.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN dimsubject.studyid IS 'Study Identifier';
COMMENT ON COLUMN dimsubject.status IS 'Status';
COMMENT ON COLUMN dimsubject.exitdate IS 'Exit Date';
COMMENT ON COLUMN dimsubject.subjectstartdisposition IS 'Subject Start Disposition';
COMMENT ON COLUMN dimsubject.subjectexitdisposition IS 'Subject Exit Disposition';
COMMENT ON COLUMN dimsubject.subjectdaystartdt IS 'Subject Start Date';
COMMENT ON COLUMN dimsubject.subjectdaysenddt IS 'Subject End Date';
COMMENT ON COLUMN dimsubject.thismonth IS 'This Month';
COMMENT ON COLUMN dimsubject.thismonthsubjectdays IS 'This Month Subject Days';
COMMENT ON COLUMN dimsubject.cumulativesubjectdays IS 'Cumulative Subject Days';
COMMENT ON COLUMN dimsubject.totalsubjectdays IS 'Total Subject Days';
COMMENT ON COLUMN dimsubject.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN dimsubject.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE dimvisitrequiredfields IS 'Visit Required Fields';
COMMENT ON COLUMN dimvisitrequiredfields.studyid IS 'Study Identifier';
COMMENT ON COLUMN dimvisitrequiredfields.visitnum IS 'Visit Number';
COMMENT ON COLUMN dimvisitrequiredfields.visit IS 'Visit';
COMMENT ON COLUMN dimvisitrequiredfields.formid IS 'Form Identifier';
COMMENT ON COLUMN dimvisitrequiredfields.primaryendpointfields IS 'Primary Endpoint Fields';
COMMENT ON COLUMN dimvisitrequiredfields.secondaryendpointfields IS 'Secondary Endpoint Fields';
COMMENT ON COLUMN dimvisitrequiredfields.sdvfields IS 'SDV Fields';
COMMENT ON COLUMN dimvisitrequiredfields.fields IS 'Fields';
COMMENT ON COLUMN dimvisitrequiredfields.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN dimvisitrequiredfields.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE factformdata IS 'Fact Form Data';
COMMENT ON COLUMN factformdata.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN factformdata.studyid IS 'Study Identifier';
COMMENT ON COLUMN factformdata.siteid IS 'Site Identifier';
COMMENT ON COLUMN factformdata.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN factformdata.formid IS 'Form Identifier';
COMMENT ON COLUMN factformdata.visit IS 'Visit';
COMMENT ON COLUMN factformdata.visitseq IS 'Visit Sequence';
COMMENT ON COLUMN factformdata.formseq IS 'Form Sequence';
COMMENT ON COLUMN factformdata.dataentrydate IS 'Data Entry Date';
COMMENT ON COLUMN factformdata.datacollecteddate IS 'datacollecteddate';
COMMENT ON COLUMN factformdata.sdvdate IS 'sdvdate';
COMMENT ON COLUMN factformdata.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN factformdata.formname IS 'Form Name';
COMMENT ON COLUMN factformdata.isprimaryendpoint IS 'Is Primary Endpoint';
COMMENT ON COLUMN factformdata.issecondaryendpoint IS 'Is Secondary Endpoint';
COMMENT ON COLUMN factformdata.issdv IS 'Is SDV';
COMMENT ON COLUMN factformdata.isrequired IS 'Is Required';
COMMENT ON COLUMN factformdata.formdefuniquekey IS 'Form Unique Key';
COMMENT ON COLUMN factformdata.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE factsiteperformance IS 'Fact Site Performance';
COMMENT ON COLUMN factsiteperformance.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN factsiteperformance.studyid IS 'Study Identifier';
COMMENT ON COLUMN factsiteperformance.studyname IS 'Study Name';
COMMENT ON COLUMN factsiteperformance.siteid IS 'Site Identifier';
COMMENT ON COLUMN factsiteperformance.sitename IS 'Site Name';
COMMENT ON COLUMN factsiteperformance.sitecro IS 'Site CRO';
COMMENT ON COLUMN factsiteperformance.sitecountry IS 'Site Country';
COMMENT ON COLUMN factsiteperformance.siteregion IS 'Site Region';
COMMENT ON COLUMN factsiteperformance.sitecraname IS 'Site CRA Name';
COMMENT ON COLUMN factsiteperformance.subjects_screened_count IS 'Subjects Screened Count';
COMMENT ON COLUMN factsiteperformance.failed_screen_count IS 'Failed Screen Count';
COMMENT ON COLUMN factsiteperformance.site_active_days_count IS 'Site Active Days Count';
COMMENT ON COLUMN factsiteperformance.enrolled_count IS 'Enrolled Count';
COMMENT ON COLUMN factsiteperformance.withdrawn_count IS 'Withdrawn Count';
COMMENT ON COLUMN factsiteperformance.open_query_count IS 'Open Query Count';
COMMENT ON COLUMN factsiteperformance.ae_count IS 'Subject Current Count of AEs';
COMMENT ON COLUMN factsiteperformance.dv_count IS 'Subject Current Count of Deviations';
COMMENT ON COLUMN factsiteperformance.subject_days_count IS 'Subject Days Count';
COMMENT ON COLUMN factsiteperformance.screen_failure_rate IS 'Screen Failure Rate';
COMMENT ON COLUMN factsiteperformance.enrollment_rate IS 'Enrollment Rate';
COMMENT ON COLUMN factsiteperformance.withdrawal_rate IS 'Withdrawal Rate';
COMMENT ON COLUMN factsiteperformance.open_query_rate IS 'Open Query Rate';
COMMENT ON COLUMN factsiteperformance.ae_rate IS 'AE Rate';
COMMENT ON COLUMN factsiteperformance.pd_rate IS 'PD Rate';
COMMENT ON COLUMN factsiteperformance.subject_visits IS 'Subject Visits';
COMMENT ON COLUMN factsiteperformance.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE factsubjectvisit IS 'Fact Subject Visit';
COMMENT ON COLUMN factsubjectvisit.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN factsubjectvisit.studyid IS 'Study Identifier';
COMMENT ON COLUMN factsubjectvisit.studyname IS 'Study Name';
COMMENT ON COLUMN factsubjectvisit.siteid IS 'Site Identifier';
COMMENT ON COLUMN factsubjectvisit.sitename IS 'Site Name';
COMMENT ON COLUMN factsubjectvisit.sitecountry IS 'Site Country';
COMMENT ON COLUMN factsubjectvisit.siteregion IS 'Site Region';
COMMENT ON COLUMN factsubjectvisit.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN factsubjectvisit.exitdate IS 'Subject Study Exit Date';
COMMENT ON COLUMN factsubjectvisit.visit IS 'Visit Name';
COMMENT ON COLUMN factsubjectvisit.visitnum IS 'Visit Number';
COMMENT ON COLUMN factsubjectvisit.visitdy IS 'Visit Day (from start of study)';
COMMENT ON COLUMN factsubjectvisit.visitwindowbefore IS 'Acceptable Visit Window Before Visit Day (in days)';
COMMENT ON COLUMN factsubjectvisit.visitwindowafter IS 'Acceptable Visit Window After Visit Day (in days)';
COMMENT ON COLUMN factsubjectvisit.first_visit IS 'Start Date of First Visit';
COMMENT ON COLUMN factsubjectvisit.expectedvisitdate IS 'Expected Visit Date';
COMMENT ON COLUMN factsubjectvisit.windowopen IS 'Window Open';
COMMENT ON COLUMN factsubjectvisit.windowclosed IS 'Window Closed';
COMMENT ON COLUMN factsubjectvisit.svmod_visitnum IS 'Most Recent Visit Number';
COMMENT ON COLUMN factsubjectvisit.svmod_visit IS 'Most Recent Visit';
COMMENT ON COLUMN factsubjectvisit.visit_start_dtc IS 'Visit Start Date';
COMMENT ON COLUMN factsubjectvisit.visit_end_dtc IS 'Visit End Date';
COMMENT ON COLUMN factsubjectvisit.visitseq IS 'Visit Sequence';
COMMENT ON COLUMN factsubjectvisit.expected IS 'Expected';
COMMENT ON COLUMN factsubjectvisit.visit_days IS 'Subject Visit Days from First Visit';
COMMENT ON COLUMN factsubjectvisit.category IS 'Query Age Category Bucket';
COMMENT ON COLUMN factsubjectvisit.schedule_compliance IS 'Schedule Compliance';
COMMENT ON COLUMN factsubjectvisit.trunc_month IS 'Visit Start Month';
COMMENT ON COLUMN factsubjectvisit.latestvisit IS 'Latest Visit';
COMMENT ON COLUMN factsubjectvisit.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE dimstudy IS 'Study Listing';
COMMENT ON COLUMN dimstudy.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN dimstudy.studyid IS 'Study Identifier';
COMMENT ON COLUMN dimstudy.studyname IS 'Study Name';
COMMENT ON COLUMN dimstudy.studydescription IS 'Study Description';
COMMENT ON COLUMN dimstudy.studystatus IS 'Study Status';
COMMENT ON COLUMN dimstudy.studyphase IS 'Study Phase';
COMMENT ON COLUMN dimstudy.studysponsor IS 'Study Sponsor';
COMMENT ON COLUMN dimstudy.therapeuticarea IS 'Therapeutic Area';
COMMENT ON COLUMN dimstudy.program IS 'Study Program';
COMMENT ON COLUMN dimstudy.medicalindication IS 'Medical Indication';
COMMENT ON COLUMN dimstudy.studystartdate IS 'Study Start Date';
COMMENT ON COLUMN dimstudy.studycompletiondate IS 'Study Completion Date';
COMMENT ON COLUMN dimstudy.planned_lpi IS 'Last Patient In Planned Date';
COMMENT ON COLUMN dimstudy.first_site_activation_planned_date IS 'First Site Activation Planned Date';
COMMENT ON COLUMN dimstudy.first_site_activation_actual_date IS 'First Site Activation Actual Date';
COMMENT ON COLUMN dimstudy.enrollment_count IS 'Total Enrolled';
COMMENT ON COLUMN dimstudy.current_count_sites_activated IS 'Current Count Sites Activated';
COMMENT ON COLUMN dimstudy.latest_planned_count_sites_activated IS 'Latest Planned Count Sites Activated';
COMMENT ON COLUMN dimstudy.study_subjects IS 'Study Subjects';
COMMENT ON COLUMN dimstudy.site_activation_completion_date IS 'Site Activation Completion Date';
COMMENT ON COLUMN dimstudy.latest_planned_date_for_last_site_activated IS 'Latest Planned Date For Last Site Activated';
COMMENT ON COLUMN dimstudy.subject_days IS 'Subject Number of Study Days';
COMMENT ON COLUMN dimstudy.study_planned_completion_date IS 'Study Planned Completion Date';
COMMENT ON COLUMN dimstudy.target_enrollment_count IS 'Target Enrollment Count';
COMMENT ON COLUMN dimstudy.current_enrollment_count IS 'Current Enrollment Count';
COMMENT ON COLUMN dimstudy.site_activation_projected_date IS 'Projected Site Activation Complete Date';
COMMENT ON COLUMN dimstudy.logistic_lsi_projected_date IS 'Logistic LSI Projected Date';
COMMENT ON COLUMN dimstudy.comprehend_update_time IS 'Comprehend Update Time';


COMMENT ON TABLE factadverseevents IS 'Fact Adverse Events';
COMMENT ON COLUMN factadverseevents.siteid IS 'Site Identifier';
COMMENT ON COLUMN factadverseevents.studyid IS 'Study Identifier';
COMMENT ON COLUMN factadverseevents.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN factadverseevents.month_trunc IS 'Month Trunc';
COMMENT ON COLUMN factadverseevents.aeseq IS 'Adverse Event Sequence';
COMMENT ON COLUMN factadverseevents.objectuniquekey IS 'Unique edge to CCDM AE';
COMMENT ON COLUMN factadverseevents.aeser IS 'Serious (e.g. Serious, Non-Serious, Unknown)';
COMMENT ON COLUMN factadverseevents.aerelnst IS 'Is AE Related to the Drug/Device? (e.g. Yes, No, or Unknown)';
COMMENT ON COLUMN factadverseevents.category IS 'Query Age Category Bucket';
COMMENT ON COLUMN factadverseevents.aeverbatim IS 'Adverse Event Verbatim Term';
COMMENT ON COLUMN factadverseevents.aeterm IS 'Adverse Event Primary Term';
COMMENT ON COLUMN factadverseevents.aebodsys IS 'Adverse Event Body System (or SOC)';
COMMENT ON COLUMN factadverseevents.aestdtc IS 'Adverse Event Start Date';
COMMENT ON COLUMN factadverseevents.aeendtc IS 'Adverse Event End Date';
COMMENT ON COLUMN factadverseevents.aesev IS 'Severity (e.g. Mild, Moderate, Severe)';
COMMENT ON COLUMN factadverseevents.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN factadverseevents.study_week_number IS 'Study Week Number';
COMMENT ON COLUMN factadverseevents.duration IS 'Adverse Event Duration (seconds)';


COMMENT ON TABLE factportfoliodaily IS 'Fact Portfolio Daily';
COMMENT ON COLUMN factportfoliodaily.date_dim_id IS 'Static Date Identifier';
COMMENT ON COLUMN factportfoliodaily.studyid IS 'Study Identifier';
COMMENT ON COLUMN factportfoliodaily.siteid IS 'Site Identifier';
COMMENT ON COLUMN factportfoliodaily.protocoldeviations IS 'Protocol Deviations';
COMMENT ON COLUMN factportfoliodaily.subjectdays IS 'Subject Days';
COMMENT ON COLUMN factportfoliodaily.adverseevents IS 'Adverse Events';
COMMENT ON COLUMN factportfoliodaily.subjectsenrolled IS 'Subjects Enrolled';
COMMENT ON COLUMN factportfoliodaily.sitedays IS 'Site Days';
COMMENT ON COLUMN factportfoliodaily.plannedenrollmentcount IS 'Planned Enrollment Count';
COMMENT ON COLUMN factportfoliodaily.consented IS 'Consented';
COMMENT ON COLUMN factportfoliodaily.consentfailures IS 'Consent Failures';
COMMENT ON COLUMN factportfoliodaily.screened IS 'Screened';
COMMENT ON COLUMN factportfoliodaily.screenfailures IS 'Screen Failures';
COMMENT ON COLUMN factportfoliodaily.randomized IS 'Randomized';
COMMENT ON COLUMN factportfoliodaily.randomizationfailures IS 'Randomization Failures';
COMMENT ON COLUMN factportfoliodaily.withdrawn IS 'Withdrawn';
COMMENT ON COLUMN factportfoliodaily.evaluable IS 'Evaluable';
COMMENT ON COLUMN factportfoliodaily.evaluablefailures IS 'Evaluable Failures';
COMMENT ON COLUMN factportfoliodaily.openquerycount IS 'Open Query Count';
COMMENT ON COLUMN factportfoliodaily.openedissues IS 'Opene Dissues';
COMMENT ON COLUMN factportfoliodaily.resolvedissues IS 'Resolve Dissues';
COMMENT ON COLUMN factportfoliodaily.closedissues IS 'Close Dissues';
COMMENT ON COLUMN factportfoliodaily.closedresolvedissues IS 'Closed Resolve Dissues';
COMMENT ON COLUMN factportfoliodaily.siteissueresolutiondays IS 'Site Issue Resolution Days';
COMMENT ON COLUMN factportfoliodaily.queryresolutiondays IS 'Query Resolution Days';
COMMENT ON COLUMN factportfoliodaily.queryopenedcount IS 'Query Opened Count';
COMMENT ON COLUMN factportfoliodaily.queryansweredcount IS 'Query Answered Count';
COMMENT ON COLUMN factportfoliodaily.querycancelledcount IS 'Query Cancelled Count';
COMMENT ON COLUMN factportfoliodaily.queryansweredclosedcount IS 'Query Answered Closed Count';
COMMENT ON COLUMN factportfoliodaily.queryansweredcancelledcount IS 'Query Answered Cancelled Count';
COMMENT ON COLUMN factportfoliodaily.queryclosedcount IS 'Query Closed Count';
COMMENT ON COLUMN factportfoliodaily.subjectvisitsonschedule IS 'Subject Visits On Schedule';
COMMENT ON COLUMN factportfoliodaily.subjectvisits IS 'Subject Visits';
COMMENT ON COLUMN factportfoliodaily.primaryendpointpopulatedrequiredfields IS 'Primary Endpoint Populated Required Fields';
COMMENT ON COLUMN factportfoliodaily.expectedrequiredprimaryendpointfields IS 'Expected Required Primary Endpoint Fields';
COMMENT ON COLUMN factportfoliodaily.secondaryendpointpopulatedrequiredfields IS 'Secondary Endpoint Populated Required Fields';
COMMENT ON COLUMN factportfoliodaily.expectedrequiredsecondaryendpointfields IS 'Expected Required Secondary Endpoint Fields';
COMMENT ON COLUMN factportfoliodaily.sdvpopulatedrequiredfields IS 'SDV Populated Required Fields';
COMMENT ON COLUMN factportfoliodaily.expectedrequiredsdvfields IS 'Expected Required SDV Fields';
COMMENT ON COLUMN factportfoliodaily.populatedrequiredfields IS 'Populated Required Fields';
COMMENT ON COLUMN factportfoliodaily.expectedrequiredfields IS 'Expected Required Fields';
COMMENT ON COLUMN factportfoliodaily.formdatacollecteddays IS 'Formdata Collected Days';
COMMENT ON COLUMN factportfoliodaily.primaryendpointformdatacollecteddays IS 'Primary Endpoint Form Data Collected Days';
COMMENT ON COLUMN factportfoliodaily.collectedformscount IS 'Collected Forms Count';
COMMENT ON COLUMN factportfoliodaily.primaryendpointcollectedforms IS 'Primary Endpoint Collected Forms';
COMMENT ON COLUMN factportfoliodaily.missedtrialvisits IS 'Missed Trial Visits';
COMMENT ON COLUMN factportfoliodaily.latetrialvisits IS 'Late Trial Visits';
COMMENT ON COLUMN factportfoliodaily.earlytrialvisits IS 'Early Trial Visits';
COMMENT ON COLUMN factportfoliodaily.plannedtrialvisits IS 'Planned Trial Visits';
COMMENT ON COLUMN factportfoliodaily.query_oldest_age_count IS 'Query Oldest Age Count';

COMMENT ON TABLE kpisummary IS 'KPI Summary';
COMMENT ON COLUMN kpisummary.studyid IS 'Study Identifier';
COMMENT ON COLUMN kpisummary.siteid IS 'Site Identifier';
COMMENT ON COLUMN kpisummary.current_studydays IS 'Current Study Days';
COMMENT ON COLUMN kpisummary.current_sitedays IS 'Current Site Days';
COMMENT ON COLUMN kpisummary.current_protocoldeviations IS 'Current Protocol Deviations';
COMMENT ON COLUMN kpisummary.current_subjectdays IS 'Current Subject Days';
COMMENT ON COLUMN kpisummary.current_adverseevents IS 'Current Adverse Events';
COMMENT ON COLUMN kpisummary.current_subjectsenrolled IS 'Current Subjects Enrolled';
COMMENT ON COLUMN kpisummary.current_consented IS 'Current Consented';
COMMENT ON COLUMN kpisummary.current_consentfailures IS 'Current Consent Failures';
COMMENT ON COLUMN kpisummary.current_screened IS 'Current Screened';
COMMENT ON COLUMN kpisummary.current_screenfailures IS 'Current Screen Failures';
COMMENT ON COLUMN kpisummary.current_randomized IS 'Current Randomized';
COMMENT ON COLUMN kpisummary.current_randomizationfailures IS 'Current Randomization Failures';
COMMENT ON COLUMN kpisummary.current_withdrawn IS 'Current Withdrawn';
COMMENT ON COLUMN kpisummary.current_evaluable IS 'Current Evaluable';
COMMENT ON COLUMN kpisummary.current_evaluablefailures IS 'Current Evaluable Failures';
COMMENT ON COLUMN kpisummary.current_openqueries IS 'Current Open Queries';
COMMENT ON COLUMN kpisummary.previous_studydays IS 'Previous Study Days';
COMMENT ON COLUMN kpisummary.previous_sitedays IS 'Previous Site Days';
COMMENT ON COLUMN kpisummary.previous_protocoldeviations IS 'Previous Protocol Deviations';
COMMENT ON COLUMN kpisummary.previous_subjectdays IS 'Previous Subject Days';
COMMENT ON COLUMN kpisummary.previous_adverseevents IS 'Previous Adverse Events';
COMMENT ON COLUMN kpisummary.previous_subjectsenrolled IS 'Previous Subjects Enrolled';
COMMENT ON COLUMN kpisummary.previous_consented IS 'Previous Consented';
COMMENT ON COLUMN kpisummary.previous_consentfailures IS 'Previous Consent Failures';
COMMENT ON COLUMN kpisummary.previous_screened IS 'Previous Screened';
COMMENT ON COLUMN kpisummary.previous_screenfailures IS 'Previous Screen Failures';
COMMENT ON COLUMN kpisummary.previous_randomized IS 'Previous Randomized';
COMMENT ON COLUMN kpisummary.previous_randomizationfailures IS 'Previous Randomization Failures';
COMMENT ON COLUMN kpisummary.previous_withdrawn IS 'Previous Withdrawn';
COMMENT ON COLUMN kpisummary.previous_evaluable IS 'Previous Evaluable';
COMMENT ON COLUMN kpisummary.previous_evaluablefailures IS 'Previous Evaluable Failures';
COMMENT ON COLUMN kpisummary.previous_openqueries IS 'Previous Open Queries';
COMMENT ON COLUMN kpisummary.current_subjectcount IS 'Current Subject Count';
COMMENT ON COLUMN kpisummary.previous_subjectcount IS 'Previous Subject Count';
COMMENT ON COLUMN kpisummary.current_siteissueresolutiondays IS 'Current Site Issue Resolution Days';
COMMENT ON COLUMN kpisummary.previous_siteissueresolutiondays IS 'Previous Site Issue Resolution Days';
COMMENT ON COLUMN kpisummary.current_closedissues IS 'Current Closed Issues';
COMMENT ON COLUMN kpisummary.previous_closedissues IS 'Previous Closed Issues';
COMMENT ON COLUMN kpisummary.current_expectedrequiredfields IS 'Current Expected Required Fields';
COMMENT ON COLUMN kpisummary.current_populatedrequiredfields IS 'Current Populated Required Fields';
COMMENT ON COLUMN kpisummary.current_expectedprimaryendpointfields IS 'Current Expected Primary Endpoint Fields';
COMMENT ON COLUMN kpisummary.current_populatedprimaryendpointfields IS 'Current Populated Primary Endpoint Fields';
COMMENT ON COLUMN kpisummary.current_expectedrequiredsdvfields IS 'Current Expected Required SDV Fields';
COMMENT ON COLUMN kpisummary.current_populatedsdvrequiredfields IS 'Current Populated SDV Required Fields';
COMMENT ON COLUMN kpisummary.current_formdatacollecteddays IS 'Current Form Data Collected Days';
COMMENT ON COLUMN kpisummary.current_primaryendpointformdatacollecteddays IS 'Current Primary Endpoint Form Data Collected Days';
COMMENT ON COLUMN kpisummary.current_collectedformscounts IS 'Current Collected Forms Counts';
COMMENT ON COLUMN kpisummary.current_primaryendpointcollectedforms IS 'Current Primary Endpoint Collected Forms';
COMMENT ON COLUMN kpisummary.current_querycount IS 'Current Query Count';
COMMENT ON COLUMN kpisummary.current_queryopencount IS 'Current Query Open Count';
COMMENT ON COLUMN kpisummary.previous_expectedrequiredfields IS 'Previous Expected Required Fields';
COMMENT ON COLUMN kpisummary.previous_populatedrequiredfields IS 'Previous Populated Required Fields';
COMMENT ON COLUMN kpisummary.previous_expectedprimaryendpointfields IS 'Previous Expected Primary Endpoint Fields';
COMMENT ON COLUMN kpisummary.previous_populatedprimaryendpointfields IS 'Previous Populated Primary Endpoint Fields';
COMMENT ON COLUMN kpisummary.previous_expectedrequiredsdvfields IS 'Previous Expected Required SDV Fields';
COMMENT ON COLUMN kpisummary.previous_populatedsdvrequiredfields IS 'Previous Populated SDV Required Fields';
COMMENT ON COLUMN kpisummary.previous_formdatacollecteddays IS 'Previous Form Data Collected Days';
COMMENT ON COLUMN kpisummary.previous_primaryendpointformdatacollecteddays IS 'Previous Primary Endpoint Form Data Collected Days';
COMMENT ON COLUMN kpisummary.previous_collectedformscounts IS 'Previous Collected Forms Counts';
COMMENT ON COLUMN kpisummary.previous_primaryendpointcollectedforms IS 'Previous Primary Endpoint Collected Forms';
COMMENT ON COLUMN kpisummary.previous_querycount IS 'Previous Query Count';
COMMENT ON COLUMN kpisummary.previous_queryopencount IS 'Previous Query Open Count';
COMMENT ON COLUMN kpisummary.current_subjectvisits IS 'Current Subject Visits';
COMMENT ON COLUMN kpisummary.current_subjectvisitsonschedule IS 'Current Subject Visits On Schedule';
COMMENT ON COLUMN kpisummary.previous_subjectvisits IS 'Previous Subject Visits';
COMMENT ON COLUMN kpisummary.previous_subjectvisitsonschedule IS 'Previous Subject Visits On Schedule';
COMMENT ON COLUMN kpisummary.current_queryresolutiondays IS 'Current Query Resolution Days';
COMMENT ON COLUMN kpisummary.current_plannedtrialvisits IS 'Current Planned Trial Visits';
COMMENT ON COLUMN kpisummary.current_missedtrialvisits IS 'Current Missed Trial Visits';
COMMENT ON COLUMN kpisummary.current_latetrialvisits IS 'Current Late Trial Visits';
COMMENT ON COLUMN kpisummary.previous_queryresolutiondays IS 'Previous Query Resolution Days';
COMMENT ON COLUMN kpisummary.previous_plannedtrialvisits IS 'Previous Planned Trial Visits';
COMMENT ON COLUMN kpisummary.previous_missedtrialvisits IS 'Previous Missed Trial Visits';
COMMENT ON COLUMN kpisummary.previous_latetrialvisits IS 'Previous Late Trial Visits';
COMMENT ON COLUMN kpisummary.current_openagedqueries IS 'Current Open Aged Queries';
COMMENT ON COLUMN kpisummary.previous_openagedqueries IS 'Previous Open Aged Queries';
COMMENT ON COLUMN kpisummary.comprehend_update_time IS 'Comprehend Update Time';


COMMENT ON TABLE dimsitedates IS 'Site Date Series';
COMMENT ON COLUMN dimsitedates.studyid IS 'Study Identifier';
COMMENT ON COLUMN dimsitedates.siteid IS 'Site Identifier';
COMMENT ON COLUMN dimsitedates.date_actual IS 'Actual Date';
COMMENT ON COLUMN dimsitedates.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_ae_rate_by_subject_days_per_month IS 'Protocol Deviation Rate by Subject Days Per Month';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days_per_month.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days_per_month.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days_per_month.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days_per_month.month_trunc IS 'Adverse Event Start Month';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days_per_month.subject_days_weight_ratio_per_site IS 'Adverse Event Subject Days/Weight Ratio Per Site';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days_per_month.subject_days_weight_ratio_per_month IS 'Adverse Event Subject Days/Weight Ratio Per Month';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days_per_month.subject_days_count IS 'Count of Subject Days';
COMMENT ON COLUMN rpt_ae_rate_by_subject_days_per_month.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_pd_rate_by_subject_days_per_month IS 'Protocol Deviation Rate by Subject Days Per Month';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days_per_month.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days_per_month.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days_per_month.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days_per_month.month_trunc IS 'Deviation Start Month';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days_per_month.subject_days_weight_ratio IS 'Deviation Subject Days/Weight Ratio';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days_per_month.subject_days_count IS 'Count of Subject Days';
COMMENT ON COLUMN rpt_pd_rate_by_subject_days_per_month.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_oversight_metrics IS 'Oversight Metrics';
COMMENT ON COLUMN rpt_oversight_metrics.metricid IS 'Metric Identifier';
COMMENT ON COLUMN rpt_oversight_metrics.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_oversight_metrics.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_oversight_metrics.numerator IS 'Metric Numerator';
COMMENT ON COLUMN rpt_oversight_metrics.denominator IS 'Metric Denominator';
COMMENT ON COLUMN rpt_oversight_metrics.invalidvalue IS 'Whether the metric value is invalid';
COMMENT ON COLUMN rpt_oversight_metrics.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_oversight_metrics.studyprogram IS 'Study Program';
COMMENT ON COLUMN rpt_oversight_metrics.studymedicalindication IS 'Study Medical Indication';
COMMENT ON COLUMN rpt_oversight_metrics.studyphase IS 'Study Phase';
COMMENT ON COLUMN rpt_oversight_metrics.studytherapeuticarea IS 'Study Therapeutic Area';
COMMENT ON COLUMN rpt_oversight_metrics.studycronames IS 'Study Contract Research Organization (CRO) Names';
COMMENT ON COLUMN rpt_oversight_metrics.studystartdate IS 'Study Start Date';
COMMENT ON COLUMN rpt_oversight_metrics.studystatus IS 'Study Status';
COMMENT ON COLUMN rpt_oversight_metrics.studydescription IS 'Study Description';
COMMENT ON COLUMN rpt_oversight_metrics.studyregions IS 'Study Regions';
COMMENT ON COLUMN rpt_oversight_metrics.studysponsor IS 'Study Sponsor';
COMMENT ON COLUMN rpt_oversight_metrics.studyplannedenddate IS 'Study Planned End Date';
COMMENT ON COLUMN rpt_oversight_metrics.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_oversight_metrics.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_oversight_metrics.sitecity IS 'Site City';
COMMENT ON COLUMN rpt_oversight_metrics.sitestate IS 'Site State';
COMMENT ON COLUMN rpt_oversight_metrics.sitepostal IS 'Site Postal Code';
COMMENT ON COLUMN rpt_oversight_metrics.siteinvestigatorname IS 'Site Investigator Name';
COMMENT ON COLUMN rpt_oversight_metrics.sitecraname IS 'Site CRA Name';
COMMENT ON COLUMN rpt_oversight_metrics.siteactivationdate IS 'Site Activation Date';
COMMENT ON COLUMN rpt_oversight_metrics.sitedeactivationdate IS 'Site Deactivation Date';
COMMENT ON COLUMN rpt_oversight_metrics.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_oversight_metrics.siteenrolledcount IS 'Site Enrolled Count';
COMMENT ON COLUMN rpt_oversight_metrics.sitecro IS 'Site Clinical Research Organization (CRO)';
COMMENT ON COLUMN rpt_oversight_metrics.studycurrentmilestone IS 'Study Current Milestone';
COMMENT ON COLUMN rpt_oversight_metrics.studycurrentmilestoneplanneddate IS 'Study Current Milestone Planned Date';
COMMENT ON COLUMN rpt_oversight_metrics.studycurrentmilestoneprojecteddate IS 'Study Current Milestone Projected Date';
COMMENT ON COLUMN rpt_oversight_metrics.studycurrentsiteactivationcount IS 'Study Current Site Activation Count';
COMMENT ON COLUMN rpt_oversight_metrics.studytargetsiteactivationcount IS 'Study Target Site Activation Count';
COMMENT ON COLUMN rpt_oversight_metrics.studyactualenrollmentcount IS 'Study Actual Enrollment Count';
COMMENT ON COLUMN rpt_oversight_metrics.studyplannedenrollmentcount IS 'Study Planned Enrollment Count';
COMMENT ON COLUMN rpt_oversight_metrics.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_subject_disposition IS 'Subject Dispositions';
COMMENT ON COLUMN rpt_subject_disposition.comprehendid IS 'Comprehend Identifer';
COMMENT ON COLUMN rpt_subject_disposition.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_subject_disposition.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_subject_disposition.program IS 'Study Program';
COMMENT ON COLUMN rpt_subject_disposition.medicalindication IS 'Study Medical Indication';
COMMENT ON COLUMN rpt_subject_disposition.studyphase IS 'Study Phase';
COMMENT ON COLUMN rpt_subject_disposition.therapeuticarea IS 'Study Therapeutic Area';
COMMENT ON COLUMN rpt_subject_disposition.studydescription IS 'Study Description';
COMMENT ON COLUMN rpt_subject_disposition.studysponsor IS 'Study Sponsor';
COMMENT ON COLUMN rpt_subject_disposition.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_subject_disposition.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_subject_disposition.sitecro IS 'Site Contract Research Organization';
COMMENT ON COLUMN rpt_subject_disposition.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_subject_disposition.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_subject_disposition.usubjid IS 'Subject Identifier';
COMMENT ON COLUMN rpt_subject_disposition.dscat IS 'Subject Disposition Category';
COMMENT ON COLUMN rpt_subject_disposition.dsterm IS 'Subject Disposition Term';
COMMENT ON COLUMN rpt_subject_disposition.dsstdtc IS 'Subject Disposition Date';
COMMENT ON COLUMN rpt_subject_disposition.dsscat IS 'Subject Disposition Sub-category';
COMMENT ON COLUMN rpt_subject_disposition.dsgrpid IS 'Subject Disposition Group ID';
COMMENT ON COLUMN rpt_subject_disposition.dsrefid IS 'Subject Disposition Reference ID';
COMMENT ON COLUMN rpt_subject_disposition.dsspid IS 'Subject Disposition Sponsor ID';
COMMENT ON COLUMN rpt_subject_disposition.dsdecod IS 'Subject Disposition Controlled Terminology';
COMMENT ON COLUMN rpt_subject_disposition.visit IS 'Visit Name';
COMMENT ON COLUMN rpt_subject_disposition.visitnum IS 'Visit Number';
COMMENT ON COLUMN rpt_subject_disposition.visitdy IS 'Planned Study Day of Visit';
COMMENT ON COLUMN rpt_subject_disposition.epoch IS 'Stage of Disposition Event';
COMMENT ON COLUMN rpt_subject_disposition.dsdtc IS 'Subject Disposition Date/Time of Collection';
COMMENT ON COLUMN rpt_subject_disposition.dsstdy IS 'Study Day Start of Disposition Event';
COMMENT ON COLUMN rpt_subject_disposition.dsseq IS 'Subject Disposition Sequence';
COMMENT ON COLUMN rpt_subject_disposition.dslabel IS 'Subject Disposition UI Label';
COMMENT ON COLUMN rpt_subject_disposition.dsevent IS 'Subject Disposition Internal Event';
COMMENT ON COLUMN rpt_subject_disposition.dsactive IS 'Is Subject Disposition Active?';
COMMENT ON COLUMN rpt_subject_disposition.dswithdrawn IS 'Is Subject Disposition Withdrawn?';
COMMENT ON COLUMN rpt_subject_disposition.dscompleted IS 'Is Subject Disposition Completed?';
COMMENT ON COLUMN rpt_subject_disposition.dsstarting IS 'Is Starting Subject Disposition?';
COMMENT ON COLUMN rpt_subject_disposition.dsid IS 'Subject Disposition UUID';
COMMENT ON COLUMN rpt_subject_disposition.study_start_disposition IS 'Study Starting Disposition';
COMMENT ON COLUMN rpt_subject_disposition.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN rpt_subject_disposition.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON COLUMN rpt_portfolio_summary_analytics.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.studyphase IS 'Study Phase';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.current_milestone IS 'Current Milestone';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.current_milestone_planned_date IS 'Current Milestone Planned Date';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.current_milestone_projected_date IS 'Current Milestone Projected Date';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.previous_milestone_planned_date IS 'Previous Milestone Planned Date';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.previous_milestone_actual_completion_date IS 'Previous Milestone Actual Completion Date';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.current_site_activation_count IS 'Current Site Activation Count';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.site_activation_planned_to_date IS 'Site Activation Count Planned to Date';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.target_site_activation_count IS 'Target Site Activation Count';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.current_enrollment_count IS 'Current Enrollment Count';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.enrollment_planned_to_date IS 'Enrollment Count Planned to Date';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.target_enrollment_count IS 'Target Enrollment Count';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.subject_days_count IS 'Subject Days Count';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.ae_count IS 'Adverse Event Count';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.ae_rate IS 'Adverse Event Rate';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.dv_count IS 'Protocol Deviation Count';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.pd_rate IS 'Protocol Deviation Rate';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.failed_screen_count IS 'Failed Screen Count';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.subjects_screened_count IS 'Subjects Screened Count';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.screenings_planned_to_date IS 'Subjects Screened Count Planned to Date';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.total_screens_planned IS 'Total Planned Subject Screens';
COMMENT ON COLUMN rpt_portfolio_summary_analytics.screen_failure_rate IS 'Screen Failure Rate';

COMMENT ON TABLE rpt_sitemilestone IS 'Site Milestone';
COMMENT ON COLUMN rpt_sitemilestone.comprehendid IS 'Comprehend Identifer';
COMMENT ON COLUMN rpt_sitemilestone.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_sitemilestone.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_sitemilestone.studydescription IS 'Study Description';
COMMENT ON COLUMN rpt_sitemilestone.studystatus IS 'Study Status';
COMMENT ON COLUMN rpt_sitemilestone.studyphase IS 'Study Phase';
COMMENT ON COLUMN rpt_sitemilestone.studysponsor IS 'Study Sponsor';
COMMENT ON COLUMN rpt_sitemilestone.therapeuticarea IS 'Therapeutic Area';
COMMENT ON COLUMN rpt_sitemilestone.program IS 'Program';
COMMENT ON COLUMN rpt_sitemilestone.medicalindication IS 'Medical Indication';
COMMENT ON COLUMN rpt_sitemilestone.studystartdate IS 'Study Start Date';
COMMENT ON COLUMN rpt_sitemilestone.studycompletiondate IS 'Study Completion Date';
COMMENT ON COLUMN rpt_sitemilestone.siteid IS 'Site Identifier';
COMMENT ON COLUMN rpt_sitemilestone.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_sitemilestone.croid IS 'Site Contract Research Organization Identifier (CRO)';
COMMENT ON COLUMN rpt_sitemilestone.sitecro IS 'Site Contract Research Organization (CRO)';
COMMENT ON COLUMN rpt_sitemilestone.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_sitemilestone.siteregion IS 'Site Region';
COMMENT ON COLUMN rpt_sitemilestone.sitecreationdate IS 'Site Creation Date';
COMMENT ON COLUMN rpt_sitemilestone.siteactivationdate IS 'Site Activation Date';
COMMENT ON COLUMN rpt_sitemilestone.sitedeactivationdate IS 'Site Deactivation Date';
COMMENT ON COLUMN rpt_sitemilestone.sitestatus IS 'Site Status';
COMMENT ON COLUMN rpt_sitemilestone.sitestatusdate IS 'Site Status Date';
COMMENT ON COLUMN rpt_sitemilestone.milestoneseq IS 'Milestone Sequence';
COMMENT ON COLUMN rpt_sitemilestone.milestonelabel IS 'Milestone Label';
COMMENT ON COLUMN rpt_sitemilestone.curbaselinedate IS 'Current Baseline Date';
COMMENT ON COLUMN rpt_sitemilestone.orgbaselinedate IS 'Original Baseline Date';
COMMENT ON COLUMN rpt_sitemilestone.planneddate IS 'Planned Date';
COMMENT ON COLUMN rpt_sitemilestone.actualdate IS 'Actual Date';
COMMENT ON COLUMN rpt_sitemilestone.datediff IS 'Date Difference in Days';
COMMENT ON COLUMN rpt_sitemilestone.ismandatory IS 'Is Mandatory';
COMMENT ON COLUMN rpt_sitemilestone.studystatusdate IS 'Study Status Date';
COMMENT ON COLUMN rpt_sitemilestone.isarchived IS 'Is Archived';
COMMENT ON COLUMN rpt_sitemilestone.istsdv IS 'Is Targeted Source Data Verification Enabled?';
COMMENT ON COLUMN rpt_sitemilestone.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN rpt_sitemilestone.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_studymilestone IS 'Study Milestone';
COMMENT ON COLUMN rpt_studymilestone.comprehendid IS 'Comprehend Identifer';
COMMENT ON COLUMN rpt_studymilestone.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_studymilestone.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_studymilestone.studydescription IS 'Study Description';
COMMENT ON COLUMN rpt_studymilestone.studystatus IS 'Study Status';
COMMENT ON COLUMN rpt_studymilestone.studyphase IS 'Study Phase';
COMMENT ON COLUMN rpt_studymilestone.studysponsor IS 'Study Sponsor';
COMMENT ON COLUMN rpt_studymilestone.therapeuticarea IS 'Therapeutic Area';
COMMENT ON COLUMN rpt_studymilestone.program IS 'Program';
COMMENT ON COLUMN rpt_studymilestone.medicalindication IS 'Medical Indication';
COMMENT ON COLUMN rpt_studymilestone.studystartdate IS 'Study Start Date';
COMMENT ON COLUMN rpt_studymilestone.studycompletiondate IS 'Study Completion Date';
COMMENT ON COLUMN rpt_studymilestone.milestoneseq IS 'Milestone Sequence';
COMMENT ON COLUMN rpt_studymilestone.milestonelabel IS 'Milestone Label';
COMMENT ON COLUMN rpt_studymilestone.curbaselinedate IS 'Current Baseline Date';
COMMENT ON COLUMN rpt_studymilestone.orgbaselinedate IS 'Original Baseline Date';
COMMENT ON COLUMN rpt_studymilestone.planneddate IS 'Planned Date';
COMMENT ON COLUMN rpt_studymilestone.actualdate IS 'Actual Date';
COMMENT ON COLUMN rpt_studymilestone.datediff IS 'Date Difference in Days';
COMMENT ON COLUMN rpt_studymilestone.ismandatory IS 'Is Mandatory';
COMMENT ON COLUMN rpt_studymilestone.iscriticalpath IS 'Is Critical Path';
COMMENT ON COLUMN rpt_studymilestone.studystatusdate IS 'Study Status Date';
COMMENT ON COLUMN rpt_studymilestone.isarchived IS 'Is Archived';
COMMENT ON COLUMN rpt_studymilestone.istsdv IS 'Is Targeted Source Data Verification Enabled?';
COMMENT ON COLUMN rpt_studymilestone.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN rpt_studymilestone.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_country_metrics IS 'Country Metrics';
COMMENT ON COLUMN rpt_country_metrics.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_country_metrics.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_country_metrics.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_country_metrics.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_country_metrics.metricid IS 'Metric Identifier';
COMMENT ON COLUMN rpt_country_metrics.numerator IS 'Metric Numerator';
COMMENT ON COLUMN rpt_country_metrics.denominator IS 'Metric Denominator';
COMMENT ON COLUMN rpt_country_metrics.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN rpt_country_metrics.comprehend_update_time IS 'Comprehend Update Time';

COMMENT ON TABLE rpt_site_metrics IS 'Site Metrics';
COMMENT ON COLUMN rpt_site_metrics.comprehendid IS 'Comprehend Identifier';
COMMENT ON COLUMN rpt_site_metrics.studyid IS 'Study Identifier';
COMMENT ON COLUMN rpt_site_metrics.studyname IS 'Study Name';
COMMENT ON COLUMN rpt_site_metrics.siteid IS 'Site Identifer';
COMMENT ON COLUMN rpt_site_metrics.sitename IS 'Site Name';
COMMENT ON COLUMN rpt_site_metrics.sitecountry IS 'Site Country';
COMMENT ON COLUMN rpt_site_metrics.metricid IS 'Metric Identifier';
COMMENT ON COLUMN rpt_site_metrics.numerator IS 'Metric Numerator';
COMMENT ON COLUMN rpt_site_metrics.denominator IS 'Metric Denominator';
COMMENT ON COLUMN rpt_site_metrics.objectuniquekey IS 'Object Unique Key';
COMMENT ON COLUMN rpt_site_metrics.comprehend_update_time IS 'Comprehend Update Time';
